package onepanel

import "context"

// BackupService covers /backups/* (cloud backup destinations and scheduled jobs).
type BackupService struct {
	ServiceBase
}

// CheckBackupUsed checks whether a backup is used.
func (s *BackupService) CheckBackupUsed(ctx context.Context, name string) (map[string]any, error) {
return s.getMap(ctx, "/backups/check/"+name)
}

// LoadBackupOptions returns the available backup options.
func (s *BackupService) LoadBackupOptions(ctx context.Context) (map[string]any, error) {
return s.getMap(ctx, "/backups/options")
}

// SearchBackups searches backup records.
func (s *BackupService) Search(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups/search", body)
}

// GetLocalDir returns the local backup directory.
func (s *BackupService) GetLocalDir(ctx context.Context) (map[string]any, error) {
return s.getMap(ctx, "/backups/local")
}

// RefreshToken refreshes the OAuth token of a backup destination.
func (s *RefreshToken) RefreshToken(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups/refresh/token", body)
}

// ListBuckets lists buckets on a storage destination.
func (s *BackupService) ListBuckets(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups/buckets", body)
}

// Create creates a new backup destination.
func (s *BackupService) Create(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups", body)
}

// CheckBackup validates the backup destination.
func (s *BackupService) CheckBackup(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups/conn/check", body)
}

// Delete deletes a backup destination.
func (s *BackupService) Delete(ctx context.Context, id uint) (map[string]any, error) {
return s.postMap(ctx, "/backups/del", IDReq{ID: id})
}

// Update updates a backup destination.
func (s *BackupService) Update(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups/update", body)
}

// RunBackup triggers a backup job.
func (s *BackupService) RunBackup(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups/backup", body)
}

// Recover restores from a backup.
func (s *BackupService) Recover(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups/recover", body)
}

// UploadForRecover uploads a local backup file to recover.
func (s *BackupService) UploadForRecover(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups/upload", body)
}

// RecoverByUpload recovers from an uploaded file.
func (s *BackupService) RecoverByUpload(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups/recover/byupload", body)
}

// LoadFilesFromBackup browses files inside a backup.
func (s *BackupService) LoadFilesFromBackup(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups/search/files", body)
}

// SearchRecords searches backup records.
func (s *BackupService) SearchRecords(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups/record/search", body)
}

// LoadRecordSize returns the total size of records.
func (s *BackupService) LoadRecordSize(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups/record/size", body)
}

// SearchRecordsByCronjob searches records generated by a cron job.
func (s *BackupService) SearchRecordsByCronjob(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups/record/search/bycronjob", body)
}

// DownloadRecord downloads a backup record.
func (s *BackupService) DownloadRecord(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups/record/download", body)
}

// DeleteRecord deletes a backup record.
func (s *BackupService) DeleteRecord(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups/record/del", body)
}

// UpdateRecordDescription updates a record's description.
func (s *BackupService) UpdateRecordDescription(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/backups/record/description/update", body)
}

// Call invokes an arbitrary /backups/* endpoint.
func (s *BackupService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// RefreshToken is exposed for the rare case where the caller wants to refresh a
// destination's OAuth token without touching the BackupService helpers.
type RefreshToken struct{ ServiceBase }

// CronjobService covers /cronjobs/* (scheduled tasks).

type CronjobService struct {
	ServiceBase
}

// Create creates a cron job.
func (s *CronjobService) Create(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/cronjobs", body)
}

// LoadNextHandle previews the next fire time.
func (s *CronjobService) LoadNextHandle(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/cronjobs/next", body)
}

// Import imports a cron job.
func (s *CronjobService) Import(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/cronjobs/import", body)
}

// Export exports cron jobs.
func (s *CronjobService) Export(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/cronjobs/export", body)
}

// LoadCronjobInfo loads a cron job's info.
func (s *CronjobService) LoadCronjobInfo(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/cronjobs/load/info", body)
}

// LoadScriptOptions lists the available scripts.
func (s *CronjobService) LoadScriptOptions(ctx context.Context) (map[string]any, error) {
return s.getMap(ctx, "/cronjobs/script/options")
}

// Delete deletes a cron job.
func (s *CronjobService) Delete(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/cronjobs/del", body)
}

// Stop stops a running cron job.
func (s *CronjobService) Stop(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/cronjobs/stop", body)
}

// Update updates a cron job.
func (s *CronjobService) Update(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/cronjobs/update", body)
}

// UpdateGroup updates the group of a cron job.
func (s *CronjobService) UpdateGroup(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/cronjobs/group/update", body)
}

// UpdateStatus updates the enable/disable status.
func (s *CronjobService) UpdateStatus(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/cronjobs/status", body)
}

// HandleOnce runs the job once.
func (s *CronjobService) HandleOnce(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/cronjobs/handle", body)
}

// Search searches cron jobs.
func (s *CronjobService) Search(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/cronjobs/search", body)
}

// SearchRecords searches job execution records.
func (s *CronjobService) SearchRecords(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/cronjobs/search/records", body)
}

// LoadRecordLog loads a record's log.
func (s *CronjobService) LoadRecordLog(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/cronjobs/records/log", body)
}

// CleanRecord cleans old records.
func (s *CronjobService) CleanRecord(ctx context.Context, body map[string]any) (map[string]any, error) {
return s.postMap(ctx, "/cronjobs/records/clean", body)
}

// Call invokes an arbitrary /cronjobs/* endpoint.
func (s *CronjobService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// FileService covers /files/* (browse, upload, download, edit, compress, share).
