package onepanel

import "context"

type BackupService struct {
	ServiceBase
}

// CheckBackupUsed checks whether a backup is used.
func (s *BackupService) CheckBackupUsed(ctx context.Context, name string) (map[string]any, error) {
	return s.getMap(ctx, "/backups/check/"+name)
}

// LoadBackupOptions returns the available backup options.
func (s *BackupService) LoadBackupOptions(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/backups/options")
}

// SearchBackups searches backup records.
func (s *BackupService) Search(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/search", body)
}

// GetLocalDir returns the local backup directory.
func (s *BackupService) GetLocalDir(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/backups/local")
}

// RefreshToken refreshes the OAuth token of a backup destination.
func (s *RefreshToken) RefreshToken(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/refresh/token", body)
}

// ListBuckets lists buckets on a storage destination.
func (s *BackupService) ListBuckets(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/buckets", body)
}

// Create creates a new backup destination.
func (s *BackupService) Create(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups", body)
}

// CheckBackup validates the backup destination.
func (s *BackupService) CheckBackup(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/conn/check", body)
}

// Delete deletes a backup destination.
func (s *BackupService) Delete(ctx context.Context, id uint) (map[string]any, error) {
	return s.postMap(ctx, "/backups/del", IDReq{ID: id})
}

// Update updates a backup destination.
func (s *BackupService) Update(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/update", body)
}

// RunBackup triggers a backup job.
func (s *BackupService) RunBackup(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/backup", body)
}

// Recover restores from a backup.
func (s *BackupService) Recover(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/recover", body)
}

// UploadForRecover uploads a local backup file to recover.
func (s *BackupService) UploadForRecover(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/upload", body)
}

// RecoverByUpload recovers from an uploaded file.
func (s *BackupService) RecoverByUpload(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/recover/byupload", body)
}

// LoadFilesFromBackup browses files inside a backup.
func (s *BackupService) LoadFilesFromBackup(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/search/files", body)
}

// SearchRecords searches backup records.
func (s *BackupService) SearchRecords(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/record/search", body)
}

// LoadRecordSize returns the total size of records.
func (s *BackupService) LoadRecordSize(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/record/size", body)
}

// SearchRecordsByCronjob searches records generated by a cron job.
func (s *BackupService) SearchRecordsByCronjob(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/record/search/bycronjob", body)
}

// DownloadRecord downloads a backup record.
func (s *BackupService) DownloadRecord(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/record/download", body)
}

// DeleteRecord deletes a backup record.
func (s *BackupService) DeleteRecord(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/record/del", body)
}

// UpdateRecordDescription updates a record's description.
func (s *BackupService) UpdateRecordDescription(ctx context.Context, body map[string]any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/record/description/update", body)
}

// Call invokes an arbitrary /backups/* endpoint.
func (s *BackupService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// RefreshToken is exposed for the rare case where the caller wants to refresh a
// destination's OAuth token without touching the BackupService helpers.
type RefreshToken struct{ ServiceBase }

// CronjobService covers /cronjobs/* (scheduled tasks).
