// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel

import (
	"context"
	"fmt"
)

// AIAccountService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type AIAccountService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *AIAccountService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTAccountsCounts — Count model accounts by provider (POST /ai/accounts/counts)
func (s *AIAccountService) POSTAccountsCounts(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/accounts/counts", body, out)
}

// POSTAccountsModels — List model account models (POST /ai/accounts/models)
func (s *AIAccountService) POSTAccountsModels(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/accounts/models", body, out)
}

// POSTAccountsModelsCreate — Create model account model (POST /ai/accounts/models/create)
func (s *AIAccountService) POSTAccountsModelsCreate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/accounts/models/create", body, out)
}

// POSTAccountsModelsDelete — Delete model account model (POST /ai/accounts/models/delete)
func (s *AIAccountService) POSTAccountsModelsDelete(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/accounts/models/delete", body, out)
}

// POSTAccountsModelsDiscover — Discover custom provider models (POST /ai/accounts/models/discover)
func (s *AIAccountService) POSTAccountsModelsDiscover(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/accounts/models/discover", body, out)
}

// POSTAccountsModelsUpdate — Update model account model (POST /ai/accounts/models/update)
func (s *AIAccountService) POSTAccountsModelsUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/accounts/models/update", body, out)
}

// AIAgentService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type AIAgentService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *AIAgentService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTAgentsAgentBind — Bind Agent role channel (POST /ai/agents/agent/bind)
func (s *AIAgentService) POSTAgentsAgentBind(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/agent/bind", body, out)
}

// POSTAgentsAgentChannels — Get Agent role channels from config file (POST /ai/agents/agent/channels)
func (s *AIAgentService) POSTAgentsAgentChannels(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/agent/channels", body, out)
}

// POSTAgentsAgentCreate — Create Agent role (POST /ai/agents/agent/create)
func (s *AIAgentService) POSTAgentsAgentCreate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/agent/create", body, out)
}

// POSTAgentsAgentDelete — Delete Agent role (POST /ai/agents/agent/delete)
func (s *AIAgentService) POSTAgentsAgentDelete(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/agent/delete", body, out)
}

// POSTAgentsAgentList — Get configured Agent roles from config file (POST /ai/agents/agent/list)
func (s *AIAgentService) POSTAgentsAgentList(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/agent/list", body, out)
}

// POSTAgentsAgentMdList — Get Agent role markdown files (POST /ai/agents/agent/md/list)
func (s *AIAgentService) POSTAgentsAgentMdList(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/agent/md/list", body, out)
}

// POSTAgentsAgentMdUpdate — Update Agent role markdown file (POST /ai/agents/agent/md/update)
func (s *AIAgentService) POSTAgentsAgentMdUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/agent/md/update", body, out)
}

// POSTAgentsAgentUnbind — Unbind Agent role channel (POST /ai/agents/agent/unbind)
func (s *AIAgentService) POSTAgentsAgentUnbind(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/agent/unbind", body, out)
}

// POSTAgentsBatchOperate — Batch operate Agent (POST /ai/agents/batch/operate)
func (s *AIAgentService) POSTAgentsBatchOperate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/batch/operate", body, out)
}

// POSTAgentsBatchSkillInstall — Batch install Agent Skill (POST /ai/agents/batch/skill/install)
func (s *AIAgentService) POSTAgentsBatchSkillInstall(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/batch/skill/install", body, out)
}

// POSTAgentsChannelDelete — Delete Agent channel config (POST /ai/agents/channel/delete)
func (s *AIAgentService) POSTAgentsChannelDelete(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/channel/delete", body, out)
}

// POSTAgentsChannelDingtalkGet — Get Agent DingTalk channel config (POST /ai/agents/channel/dingtalk/get)
func (s *AIAgentService) POSTAgentsChannelDingtalkGet(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/channel/dingtalk/get", body, out)
}

// POSTAgentsChannelDingtalkUpdate — Update Agent DingTalk channel config (POST /ai/agents/channel/dingtalk/update)
func (s *AIAgentService) POSTAgentsChannelDingtalkUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/channel/dingtalk/update", body, out)
}

// POSTAgentsChannelDiscordGet — Get Agent Discord channel config (POST /ai/agents/channel/discord/get)
func (s *AIAgentService) POSTAgentsChannelDiscordGet(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/channel/discord/get", body, out)
}

// POSTAgentsChannelDiscordUpdate — Update Agent Discord channel config (POST /ai/agents/channel/discord/update)
func (s *AIAgentService) POSTAgentsChannelDiscordUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/channel/discord/update", body, out)
}

// POSTAgentsChannelFeishuGet — Get Agent Feishu channel config (POST /ai/agents/channel/feishu/get)
func (s *AIAgentService) POSTAgentsChannelFeishuGet(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/channel/feishu/get", body, out)
}

// POSTAgentsChannelFeishuUpdate — Update Agent Feishu channel config (POST /ai/agents/channel/feishu/update)
func (s *AIAgentService) POSTAgentsChannelFeishuUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/channel/feishu/update", body, out)
}

// POSTAgentsChannelPairingApprove — Approve Agent channel pairing code (POST /ai/agents/channel/pairing/approve)
func (s *AIAgentService) POSTAgentsChannelPairingApprove(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/channel/pairing/approve", body, out)
}

// POSTAgentsChannelQqbotGet — Get Agent QQ Bot channel config (POST /ai/agents/channel/qqbot/get)
func (s *AIAgentService) POSTAgentsChannelQqbotGet(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/channel/qqbot/get", body, out)
}

// POSTAgentsChannelQqbotUpdate — Update Agent QQ Bot channel config (POST /ai/agents/channel/qqbot/update)
func (s *AIAgentService) POSTAgentsChannelQqbotUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/channel/qqbot/update", body, out)
}

// POSTAgentsChannelTelegramGet — Get Agent Telegram channel config (POST /ai/agents/channel/telegram/get)
func (s *AIAgentService) POSTAgentsChannelTelegramGet(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/channel/telegram/get", body, out)
}

// POSTAgentsChannelTelegramUpdate — Update Agent Telegram channel config (POST /ai/agents/channel/telegram/update)
func (s *AIAgentService) POSTAgentsChannelTelegramUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/channel/telegram/update", body, out)
}

// POSTAgentsChannelWecomGet — Get Agent QQ Bot channel config (POST /ai/agents/channel/wecom/get)
func (s *AIAgentService) POSTAgentsChannelWecomGet(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/channel/wecom/get", body, out)
}

// POSTAgentsChannelWecomUpdate — Update Agent WeCom channel config (POST /ai/agents/channel/wecom/update)
func (s *AIAgentService) POSTAgentsChannelWecomUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/channel/wecom/update", body, out)
}

// POSTAgentsChannelWeixinGet — Get Agent Weixin channel config (POST /ai/agents/channel/weixin/get)
func (s *AIAgentService) POSTAgentsChannelWeixinGet(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/channel/weixin/get", body, out)
}

// POSTAgentsChannelWeixinLogin — Login Agent Weixin channel (POST /ai/agents/channel/weixin/login)
func (s *AIAgentService) POSTAgentsChannelWeixinLogin(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/channel/weixin/login", body, out)
}

// POSTAgentsConfigfileGet — Get Agent config file (POST /ai/agents/config-file/get)
func (s *AIAgentService) POSTAgentsConfigfileGet(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/config-file/get", body, out)
}

// POSTAgentsConfigfileUpdate — Update Agent config file (POST /ai/agents/config-file/update)
func (s *AIAgentService) POSTAgentsConfigfileUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/config-file/update", body, out)
}

// POSTAgentsHermesChatSessions — Get Hermes chat sessions (POST /ai/agents/hermes/chat/sessions)
func (s *AIAgentService) POSTAgentsHermesChatSessions(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/hermes/chat/sessions", body, out)
}

// POSTAgentsHermesChatSessionsDelete — Delete Hermes chat session (POST /ai/agents/hermes/chat/sessions/delete)
func (s *AIAgentService) POSTAgentsHermesChatSessionsDelete(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/hermes/chat/sessions/delete", body, out)
}

// POSTAgentsHermesChatSessionsRename — Rename Hermes chat session (POST /ai/agents/hermes/chat/sessions/rename)
func (s *AIAgentService) POSTAgentsHermesChatSessionsRename(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/hermes/chat/sessions/rename", body, out)
}

// POSTAgentsModelGet — Get Agent model config (POST /ai/agents/model/get)
func (s *AIAgentService) POSTAgentsModelGet(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/model/get", body, out)
}

// POSTAgentsModelUpdate — Update Agent model config (POST /ai/agents/model/update)
func (s *AIAgentService) POSTAgentsModelUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/model/update", body, out)
}

// POSTAgentsOtherGet — Get Agent Other config (POST /ai/agents/other/get)
func (s *AIAgentService) POSTAgentsOtherGet(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/other/get", body, out)
}

// POSTAgentsOtherUpdate — Update Agent Other config (POST /ai/agents/other/update)
func (s *AIAgentService) POSTAgentsOtherUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/other/update", body, out)
}

// POSTAgentsPluginCheck — Check Agent plugin installation status (POST /ai/agents/plugin/check)
func (s *AIAgentService) POSTAgentsPluginCheck(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/plugin/check", body, out)
}

// POSTAgentsPluginInstall — Install Agent plugin (POST /ai/agents/plugin/install)
func (s *AIAgentService) POSTAgentsPluginInstall(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/plugin/install", body, out)
}

// POSTAgentsPluginUninstall — Uninstall Agent plugin (POST /ai/agents/plugin/uninstall)
func (s *AIAgentService) POSTAgentsPluginUninstall(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/plugin/uninstall", body, out)
}

// POSTAgentsPluginUpgrade — Upgrade Agent plugin (POST /ai/agents/plugin/upgrade)
func (s *AIAgentService) POSTAgentsPluginUpgrade(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/plugin/upgrade", body, out)
}

// POSTAgentsPluginsInstall — Install an OpenClaw marketplace plugin (POST /ai/agents/plugins/install)
func (s *AIAgentService) POSTAgentsPluginsInstall(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/plugins/install", body, out)
}

// POSTAgentsPluginsList — List OpenClaw plugins (POST /ai/agents/plugins/list)
func (s *AIAgentService) POSTAgentsPluginsList(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/plugins/list", body, out)
}

// POSTAgentsPluginsOperate — Operate an OpenClaw plugin (POST /ai/agents/plugins/operate)
func (s *AIAgentService) POSTAgentsPluginsOperate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/plugins/operate", body, out)
}

// POSTAgentsPluginsSearch — Search OpenClaw plugins (POST /ai/agents/plugins/search)
func (s *AIAgentService) POSTAgentsPluginsSearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/plugins/search", body, out)
}

// POSTAgentsSecurityGet — Get Agent Security config (POST /ai/agents/security/get)
func (s *AIAgentService) POSTAgentsSecurityGet(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/security/get", body, out)
}

// POSTAgentsSecurityUpdate — Update Agent Security config (POST /ai/agents/security/update)
func (s *AIAgentService) POSTAgentsSecurityUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/security/update", body, out)
}

// POSTAgentsSkillsInstall — Install Agent skill (POST /ai/agents/skills/install)
func (s *AIAgentService) POSTAgentsSkillsInstall(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/skills/install", body, out)
}

// POSTAgentsSkillsList — List Agent skills (POST /ai/agents/skills/list)
func (s *AIAgentService) POSTAgentsSkillsList(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/skills/list", body, out)
}

// POSTAgentsSkillsSearch — Search Agent skills (POST /ai/agents/skills/search)
func (s *AIAgentService) POSTAgentsSkillsSearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/skills/search", body, out)
}

// POSTAgentsSkillsUninstall — Uninstall Agent skill (POST /ai/agents/skills/uninstall)
func (s *AIAgentService) POSTAgentsSkillsUninstall(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/skills/uninstall", body, out)
}

// POSTAgentsSkillsUpdate — Update Agent skill status (POST /ai/agents/skills/update)
func (s *AIAgentService) POSTAgentsSkillsUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/skills/update", body, out)
}

// POSTAgentsWebsiteBind — Bind Agent website (POST /ai/agents/website/bind)
func (s *AIAgentService) POSTAgentsWebsiteBind(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/website/bind", body, out)
}

// POSTAgentsWebsiteUnbind — Unbind Agent website (POST /ai/agents/website/unbind)
func (s *AIAgentService) POSTAgentsWebsiteUnbind(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/agents/website/unbind", body, out)
}

// AIDomainService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type AIDomainService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *AIDomainService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTDomainBind — Bind domain (POST /ai/domain/bind)
func (s *AIDomainService) POSTDomainBind(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/domain/bind", body, out)
}

// POSTDomainGet — Get bind domain (POST /ai/domain/get)
func (s *AIDomainService) POSTDomainGet(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/domain/get", body, out)
}

// POSTDomainUpdate — Update bind domain (POST /ai/domain/update)
func (s *AIDomainService) POSTDomainUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/domain/update", body, out)
}

// AIMcpService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type AIMcpService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *AIMcpService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTMcpDomainBind — Bind Domain for mcp server (POST /ai/mcp/domain/bind)
func (s *AIMcpService) POSTMcpDomainBind(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/mcp/domain/bind", body, out)
}

// GETMcpDomainGet — Get bin Domain for mcp server (GET /ai/mcp/domain/get)
func (s *AIMcpService) GETMcpDomainGet(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/ai/mcp/domain/get", out)
}

// POSTMcpDomainUpdate — Update bind Domain for mcp server (POST /ai/mcp/domain/update)
func (s *AIMcpService) POSTMcpDomainUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/mcp/domain/update", body, out)
}

// POSTMcpServerConnectionTest — Test mcp server connection (POST /ai/mcp/server/connection/test)
func (s *AIMcpService) POSTMcpServerConnectionTest(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/mcp/server/connection/test", body, out)
}

// POSTMcpServerStatusSync — Sync mcp server status (POST /ai/mcp/server/status/sync)
func (s *AIMcpService) POSTMcpServerStatusSync(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/mcp/server/status/sync", body, out)
}

// AITensorService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type AITensorService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *AITensorService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTTensorrtCreate — Create TensorRT LLM (POST /ai/tensorrt/create)
func (s *AITensorService) POSTTensorrtCreate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/tensorrt/create", body, out)
}

// POSTTensorrtDelete — Delete TensorRT LLM (POST /ai/tensorrt/delete)
func (s *AITensorService) POSTTensorrtDelete(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/tensorrt/delete", body, out)
}

// POSTTensorrtOperate — Operate TensorRT LLM (POST /ai/tensorrt/operate)
func (s *AITensorService) POSTTensorrtOperate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/tensorrt/operate", body, out)
}

// POSTTensorrtSearch — Page TensorRT LLMs (POST /ai/tensorrt/search)
func (s *AITensorService) POSTTensorrtSearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/tensorrt/search", body, out)
}

// POSTTensorrtUpdate — Update TensorRT LLM (POST /ai/tensorrt/update)
func (s *AITensorService) POSTTensorrtUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/ai/tensorrt/update", body, out)
}

// GETkey — Search app by key (GET /apps/:key)
func (s *AppService) GETkey(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/apps/:key", out)
}

// GETDetailappidversiontype — Search app detail by appid (GET /apps/detail/:appId/:version/:type)
func (s *AppService) GETDetailappidversiontype(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/apps/detail/:appId/:version/:type", out)
}

// GETDetailNodeappkeyversion — Search app detail by appkey and version (GET /apps/detail/node/:appKey/:version)
func (s *AppService) GETDetailNodeappkeyversion(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/apps/detail/node/:appKey/:version", out)
}

// GETDetailsid — Get app detail by id (GET /apps/details/:id)
func (s *AppService) GETDetailsid(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/apps/details/:id", out)
}

// GETIconkey — Get app icon by app_id (GET /apps/icon/:key)
func (s *AppService) GETIconkey(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/apps/icon/:key", out)
}

// POSTIgnoredCancel — Cancel Ignore Upgrade App (POST /apps/ignored/cancel)
func (s *AppService) POSTIgnoredCancel(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/apps/ignored/cancel", body, out)
}

// GETIgnoredDetail — List Upgrade Ignored App (GET /apps/ignored/detail)
func (s *AppService) GETIgnoredDetail(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/apps/ignored/detail", out)
}

// POSTInstalledConfigUpdate — Update app config (POST /apps/installed/config/update)
func (s *AppService) POSTInstalledConfigUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/apps/installed/config/update", body, out)
}

// GETInstalledDeleteCheckappinstallid — Check before delete (GET /apps/installed/delete/check/:appInstallId)
func (s *AppService) GETInstalledDeleteCheckappinstallid(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/apps/installed/delete/check/:appInstallId", out)
}

// POSTInstalledIgnore — Ignore Upgrade App (POST /apps/installed/ignore)
func (s *AppService) POSTInstalledIgnore(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/apps/installed/ignore", body, out)
}

// GETInstalledInfoappinstallid — Get app install info (GET /apps/installed/info/:appInstallId)
func (s *AppService) GETInstalledInfoappinstallid(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/apps/installed/info/:appInstallId", out)
}

// GETInstalledParamsappinstallid — Search params by appInstallId (GET /apps/installed/params/:appInstallId)
func (s *AppService) GETInstalledParamsappinstallid(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/apps/installed/params/:appInstallId", out)
}

// POSTInstalledSortUpdate — Update app install sort (POST /apps/installed/sort/update)
func (s *AppService) POSTInstalledSortUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/apps/installed/sort/update", body, out)
}

// GETServiceskey — Search app service by key (GET /apps/services/:key)
func (s *AppService) GETServiceskey(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/apps/services/:key", out)
}

// GETCheck — Check backup used (GET /backups/check/{name})
func (s *BackupService) GETCheck(ctx context.Context, name string, body any, out any) error {
	return s.Get(ctx, fmt.Sprintf("/backups/check/%s", name), out)
}

// POSTFilesDownload — Download container file (POST /containers/files/download)
func (s *ContainerService) POSTFilesDownload(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/containers/files/download", body, out)
}

// GETSearchLog — Container logs (GET /containers/search/log)
func (s *ContainerService) GETSearchLog(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/containers/search/log", out)
}

// GETStatsid — Container stats (GET /containers/stats/:id)
func (s *ContainerService) GETStatsid(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/containers/stats/:id", out)
}

// CoreAuthService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type CoreAuthService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *CoreAuthService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTAuthLogin — User login (POST /core/auth/login)
func (s *CoreAuthService) POSTAuthLogin(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/auth/login", body, out)
}

// POSTAuthMfalogin — User login with mfa (POST /core/auth/mfalogin)
func (s *CoreAuthService) POSTAuthMfalogin(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/auth/mfalogin", body, out)
}

// CoreBackupsService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type CoreBackupsService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *CoreBackupsService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTBackups — Create backup account (POST /core/backups)
func (s *CoreBackupsService) POSTBackups(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/backups", body, out)
}

// GETBackupsClientclienttype — Load backup account base info (GET /core/backups/client/:clientType)
func (s *CoreBackupsService) GETBackupsClientclienttype(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/core/backups/client/:clientType", out)
}

// POSTBackupsDel — Delete backup account (POST /core/backups/del)
func (s *CoreBackupsService) POSTBackupsDel(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/backups/del", body, out)
}

// POSTBackupsRefreshToken — Refresh token (POST /core/backups/refresh/token)
func (s *CoreBackupsService) POSTBackupsRefreshToken(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/backups/refresh/token", body, out)
}

// POSTBackupsUpdate — Update backup account (POST /core/backups/update)
func (s *CoreBackupsService) POSTBackupsUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/backups/update", body, out)
}

// CoreCommandsService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type CoreCommandsService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *CoreCommandsService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTCommands — Create command (POST /core/commands)
func (s *CoreCommandsService) POSTCommands(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/commands", body, out)
}

// POSTCommandsDel — Delete command (POST /core/commands/del)
func (s *CoreCommandsService) POSTCommandsDel(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/commands/del", body, out)
}

// POSTCommandsExport — Export command (POST /core/commands/export)
func (s *CoreCommandsService) POSTCommandsExport(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/commands/export", body, out)
}

// POSTCommandsImport — Import command (POST /core/commands/import)
func (s *CoreCommandsService) POSTCommandsImport(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/commands/import", body, out)
}

// POSTCommandsList — List commands (POST /core/commands/list)
func (s *CoreCommandsService) POSTCommandsList(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/commands/list", body, out)
}

// POSTCommandsSearch — Page commands (POST /core/commands/search)
func (s *CoreCommandsService) POSTCommandsSearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/commands/search", body, out)
}

// POSTCommandsTree — Tree commands (POST /core/commands/tree)
func (s *CoreCommandsService) POSTCommandsTree(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/commands/tree", body, out)
}

// POSTCommandsUpdate — Update command (POST /core/commands/update)
func (s *CoreCommandsService) POSTCommandsUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/commands/update", body, out)
}

// POSTCommandsUpload — Upload command csv for list (POST /core/commands/upload)
func (s *CoreCommandsService) POSTCommandsUpload(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/commands/upload", body, out)
}

// CoreGroupsService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type CoreGroupsService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *CoreGroupsService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTGroups — Create group (POST /core/groups)
func (s *CoreGroupsService) POSTGroups(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/groups", body, out)
}

// POSTGroupsDel — Delete group (POST /core/groups/del)
func (s *CoreGroupsService) POSTGroupsDel(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/groups/del", body, out)
}

// POSTGroupsSearch — List groups (POST /core/groups/search)
func (s *CoreGroupsService) POSTGroupsSearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/groups/search", body, out)
}

// POSTGroupsUpdate — Update group (POST /core/groups/update)
func (s *CoreGroupsService) POSTGroupsUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/groups/update", body, out)
}

// CoreLogsService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type CoreLogsService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *CoreLogsService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTLogsClean — Clean operation logs (POST /core/logs/clean)
func (s *CoreLogsService) POSTLogsClean(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/logs/clean", body, out)
}

// POSTLogsLogin — Page login logs (POST /core/logs/login)
func (s *CoreLogsService) POSTLogsLogin(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/logs/login", body, out)
}

// POSTLogsOperation — Page operation logs (POST /core/logs/operation)
func (s *CoreLogsService) POSTLogsOperation(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/logs/operation", body, out)
}

// CoreScriptService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type CoreScriptService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *CoreScriptService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTScript — Add script (POST /core/script)
func (s *CoreScriptService) POSTScript(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/script", body, out)
}

// POSTScriptDel — Delete script (POST /core/script/del)
func (s *CoreScriptService) POSTScriptDel(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/script/del", body, out)
}

// GETScriptRun — Run script (GET /core/script/run)
func (s *CoreScriptService) GETScriptRun(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/core/script/run", out)
}

// POSTScriptSearch — Page script (POST /core/script/search)
func (s *CoreScriptService) POSTScriptSearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/script/search", body, out)
}

// POSTScriptSync — Sync script from remote (POST /core/script/sync)
func (s *CoreScriptService) POSTScriptSync(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/script/sync", body, out)
}

// POSTScriptUpdate — Update script (POST /core/script/update)
func (s *CoreScriptService) POSTScriptUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/script/update", body, out)
}

// CoreSettingsService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type CoreSettingsService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *CoreSettingsService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// GETSettingsAppsStoreConfig — Get appstore config (GET /core/settings/apps/store/config)
func (s *CoreSettingsService) GETSettingsAppsStoreConfig(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/core/settings/apps/store/config", out)
}

// POSTSettingsAppsStoreUpdate — Update appstore config (POST /core/settings/apps/store/update)
func (s *CoreSettingsService) POSTSettingsAppsStoreUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/apps/store/update", body, out)
}

// POSTSettingsBindUpdate — Update system bind info (POST /core/settings/bind/update)
func (s *CoreSettingsService) POSTSettingsBindUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/bind/update", body, out)
}

// GETSettingsInterface — Load system address (GET /core/settings/interface)
func (s *CoreSettingsService) GETSettingsInterface(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/core/settings/interface", out)
}

// GETSettingsMemo — Load dashboard memo (GET /core/settings/memo)
func (s *CoreSettingsService) GETSettingsMemo(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/core/settings/memo", out)
}

// POSTSettingsMemo — Update dashboard memo (POST /core/settings/memo)
func (s *CoreSettingsService) POSTSettingsMemo(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/memo", body, out)
}

// POSTSettingsMenuDefault — Default menu (POST /core/settings/menu/default)
func (s *CoreSettingsService) POSTSettingsMenuDefault(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/menu/default", body, out)
}

// POSTSettingsMenuUpdate — Update system setting (POST /core/settings/menu/update)
func (s *CoreSettingsService) POSTSettingsMenuUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/menu/update", body, out)
}

// POSTSettingsPortUpdate — Update system port (POST /core/settings/port/update)
func (s *CoreSettingsService) POSTSettingsPortUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/port/update", body, out)
}

// POSTSettingsProxyUpdate — Update proxy setting (POST /core/settings/proxy/update)
func (s *CoreSettingsService) POSTSettingsProxyUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/proxy/update", body, out)
}

// POSTSettingsSearch — Load system setting info (POST /core/settings/search)
func (s *CoreSettingsService) POSTSettingsSearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/search", body, out)
}

// GETSettingsSearchAvailable — Load system available status (GET /core/settings/search/available)
func (s *CoreSettingsService) GETSettingsSearchAvailable(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/core/settings/search/available", out)
}

// POSTSettingsSearchBase — Load base system setting info (POST /core/settings/search/base)
func (s *CoreSettingsService) POSTSettingsSearchBase(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/search/base", body, out)
}

// POSTSettingsSslDownload — Download system cert (POST /core/settings/ssl/download)
func (s *CoreSettingsService) POSTSettingsSslDownload(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/ssl/download", body, out)
}

// GETSettingsSslInfo — Load system cert info (GET /core/settings/ssl/info)
func (s *CoreSettingsService) GETSettingsSslInfo(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/core/settings/ssl/info", out)
}

// POSTSettingsSslReload — Reload SSL (POST /core/settings/ssl/reload)
func (s *CoreSettingsService) POSTSettingsSslReload(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/ssl/reload", body, out)
}

// POSTSettingsSslUpdate — Update system ssl (POST /core/settings/ssl/update)
func (s *CoreSettingsService) POSTSettingsSslUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/ssl/update", body, out)
}

// POSTSettingsTerminalSearch — Load system terminal setting info (POST /core/settings/terminal/search)
func (s *CoreSettingsService) POSTSettingsTerminalSearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/terminal/search", body, out)
}

// POSTSettingsTerminalUpdate — Update system terminal setting (POST /core/settings/terminal/update)
func (s *CoreSettingsService) POSTSettingsTerminalUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/terminal/update", body, out)
}

// POSTSettingsUpdate — Update system setting (POST /core/settings/update)
func (s *CoreSettingsService) POSTSettingsUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/update", body, out)
}

// GETSettingsUpgrade — Load upgrade info (GET /core/settings/upgrade)
func (s *CoreSettingsService) GETSettingsUpgrade(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/core/settings/upgrade", out)
}

// POSTSettingsUpgrade — Upgrade (POST /core/settings/upgrade)
func (s *CoreSettingsService) POSTSettingsUpgrade(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/upgrade", body, out)
}

// POSTSettingsUpgradeNotes — Load release notes by version (POST /core/settings/upgrade/notes)
func (s *CoreSettingsService) POSTSettingsUpgradeNotes(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/core/settings/upgrade/notes", body, out)
}

// GETSettingsUpgradeReleases — Load upgrade notes (GET /core/settings/upgrade/releases)
func (s *CoreSettingsService) GETSettingsUpgradeReleases(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/core/settings/upgrade/releases", out)
}

// GETBaseiooptionnetoption — Load dashboard base info (GET /dashboard/base/:ioOption/:netOption)
func (s *DashboardService) GETBaseiooptionnetoption(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/dashboard/base/:ioOption/:netOption", out)
}

// GETCurrentiooptionnetoption — Load dashboard current info (GET /dashboard/current/:ioOption/:netOption)
func (s *DashboardService) GETCurrentiooptionnetoption(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/dashboard/current/:ioOption/:netOption", out)
}

// POSTSystemRestartoperation — System restart (POST /dashboard/system/restart/:operation)
func (s *DashboardService) POSTSystemRestartoperation(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/dashboard/system/restart/:operation", body, out)
}

// GETDbname — Get databases (GET /databases/db/:name)
func (s *DatabaseService) GETDbname(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/databases/db/:name", out)
}

// GETDbItemtype — List databases (GET /databases/db/item/:type)
func (s *DatabaseService) GETDbItemtype(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/databases/db/item/:type", out)
}

// GETDbListtype — List databases (GET /databases/db/list/:type)
func (s *DatabaseService) GETDbListtype(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/databases/db/list/:type", out)
}

// POSTPgdatabaseLoad — Load postgresql database from remote (POST /databases/pg/:database/load)
func (s *DatabaseService) POSTPgdatabaseLoad(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/databases/pg/:database/load", body, out)
}

// POSTAisearch — File search: content grep + optional AI summary (POST /files/ai-search)
func (s *FileService) POSTAisearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/ai-search", body, out)
}

// POSTBatchCheck — Batch check file exist (POST /files/batch/check)
func (s *FileService) POSTBatchCheck(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/batch/check", body, out)
}

// POSTBatchDel — Batch delete file (POST /files/batch/del)
func (s *FileService) POSTBatchDel(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/batch/del", body, out)
}

// POSTBatchRole — Batch change file mode and owner (POST /files/batch/role)
func (s *FileService) POSTBatchRole(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/batch/role", body, out)
}

// POSTCheck — Check file exist (POST /files/check)
func (s *FileService) POSTCheck(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/check", body, out)
}

// POSTChunkdownload — Chunk Download file (POST /files/chunkdownload)
func (s *FileService) POSTChunkdownload(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/chunkdownload", body, out)
}

// POSTCompressStop — Stop compress task (POST /files/compress/stop)
func (s *FileService) POSTCompressStop(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/compress/stop", body, out)
}

// POSTConvert — Convert file (POST /files/convert)
func (s *FileService) POSTConvert(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/convert", body, out)
}

// POSTConvertLog — Convert file (POST /files/convert/log)
func (s *FileService) POSTConvertLog(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/convert/log", body, out)
}

// POSTDecompressStop — Stop decompress task (POST /files/decompress/stop)
func (s *FileService) POSTDecompressStop(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/decompress/stop", body, out)
}

// POSTDepthSize — Multi file size (POST /files/depth/size)
func (s *FileService) POSTDepthSize(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/depth/size", body, out)
}

// GETDownload — Download file (GET /files/download)
func (s *FileService) GETDownload(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/files/download", out)
}

// POSTFavorite — Create favorite (POST /files/favorite)
func (s *FileService) POSTFavorite(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/favorite", body, out)
}

// POSTFavoriteDel — Delete favorite (POST /files/favorite/del)
func (s *FileService) POSTFavoriteDel(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/favorite/del", body, out)
}

// POSTFavoriteSearch — List favorites (POST /files/favorite/search)
func (s *FileService) POSTFavoriteSearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/favorite/search", body, out)
}

// POSTHistoryContent — Load file history content (POST /files/history/content)
func (s *FileService) POSTHistoryContent(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/history/content", body, out)
}

// POSTHistoryDel — Delete file history record (POST /files/history/del)
func (s *FileService) POSTHistoryDel(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/history/del", body, out)
}

// POSTHistoryRestore — Restore file history record (POST /files/history/restore)
func (s *FileService) POSTHistoryRestore(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/history/restore", body, out)
}

// POSTHistorySearch — Load file history list (POST /files/history/search)
func (s *FileService) POSTHistorySearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/history/search", body, out)
}

// POSTMode — Change file mode (POST /files/mode)
func (s *FileService) POSTMode(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/mode", body, out)
}

// POSTMount — system mount (POST /files/mount)
func (s *FileService) POSTMount(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/mount", body, out)
}

// POSTPreview — Preview file content (POST /files/preview)
func (s *FileService) POSTPreview(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/preview", body, out)
}

// POSTRead — Read file by Line (POST /files/read/{type})
func (s *FileService) POSTRead(ctx context.Context, typeVal string, body any, out any) error {
	return s.Post(ctx, fmt.Sprintf("/files/read/%s", typeVal), body, out)
}

// POSTRecycleClear — Clear RecycleBin files (POST /files/recycle/clear)
func (s *FileService) POSTRecycleClear(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/recycle/clear", body, out)
}

// POSTRecycleReduce — Reduce RecycleBin files (POST /files/recycle/reduce)
func (s *FileService) POSTRecycleReduce(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/recycle/reduce", body, out)
}

// POSTRecycleSearch — List RecycleBin files (POST /files/recycle/search)
func (s *FileService) POSTRecycleSearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/recycle/search", body, out)
}

// GETRecycleStatus — Get RecycleBin status (GET /files/recycle/status)
func (s *FileService) GETRecycleStatus(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/files/recycle/status", out)
}

// POSTRemark — Set file remark (POST /files/remark)
func (s *FileService) POSTRemark(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/remark", body, out)
}

// POSTRemarks — Batch get file remarks (POST /files/remarks)
func (s *FileService) POSTRemarks(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/remarks", body, out)
}

// GETShareCheck — Check file share code (no login) (GET /files/share/check)
func (s *FileService) GETShareCheck(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/files/share/check", out)
}

// POSTShareCreate — Create temporary file share link (POST /files/share/create)
func (s *FileService) POSTShareCreate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/share/create", body, out)
}

// POSTShareDel — Delete file share by path (POST /files/share/del)
func (s *FileService) POSTShareDel(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/share/del", body, out)
}

// POSTShareDetail — Get file share detail by path (POST /files/share/detail)
func (s *FileService) POSTShareDetail(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/share/detail", body, out)
}

// GETShareDownload — Download file by share code (no login) (GET /files/share/download)
func (s *FileService) GETShareDownload(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/files/share/download", out)
}

// GETShareInfo — Get file share detail by code (no login) (GET /files/share/info)
func (s *FileService) GETShareInfo(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/files/share/info", out)
}

// GETShareQrcode — Get file share QR code image (GET /files/share/qrcode)
func (s *FileService) GETShareQrcode(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/files/share/qrcode", out)
}

// POSTShareSearch — List file shares (POST /files/share/search)
func (s *FileService) POSTShareSearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/share/search", body, out)
}

// POSTSize — Load file size (POST /files/size)
func (s *FileService) POSTSize(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/size", body, out)
}

// POSTTree — Load files tree (POST /files/tree)
func (s *FileService) POSTTree(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/tree", body, out)
}

// POSTUploadSearch — Page file (POST /files/upload/search)
func (s *FileService) POSTUploadSearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/upload/search", body, out)
}

// POSTUserGroup — system user and group (POST /files/user/group)
func (s *FileService) POSTUserGroup(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/user/group", body, out)
}

// GETWgetProcess — Wget process (GET /files/wget/process)
func (s *FileService) GETWgetProcess(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/files/wget/process", out)
}

// GETWgetProcessKeys — Process keys (GET /files/wget/process/keys)
func (s *FileService) GETWgetProcessKeys(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/files/wget/process/keys", out)
}

// POSTWgetStop — Stop wget file download (POST /files/wget/stop)
func (s *FileService) POSTWgetStop(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/files/wget/stop", body, out)
}

// HealthService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type HealthService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *HealthService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// GETCheck — Check health (GET /health/check)
func (s *HealthService) GETCheck(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/health/check", out)
}

// HostOtherService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type HostOtherService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *HostOtherService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// GETComponents — Check if a system component exists (GET /hosts/components/{name})
func (s *HostOtherService) GETComponents(ctx context.Context, name string, body any, out any) error {
	return s.Get(ctx, fmt.Sprintf("/hosts/components/%s", name), out)
}

// GETTerminalContainer — Ws container terminal (GET /hosts/terminal/container)
func (s *HostOtherService) GETTerminalContainer(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/hosts/terminal/container", out)
}

// GETTerminalLocal — Ws local terminal (GET /hosts/terminal/local)
func (s *HostOtherService) GETTerminalLocal(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/hosts/terminal/local", out)
}

// GETTerminalSsh — Ws host SSH (GET /hosts/terminal/ssh)
func (s *HostOtherService) GETTerminalSsh(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/hosts/terminal/ssh", out)
}

// OpenRestyService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type OpenRestyService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *OpenRestyService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// GETOpenresty — Load OpenResty conf (GET /openresty)
func (s *OpenRestyService) GETOpenresty(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/openresty", out)
}

// POSTBuild — Build OpenResty (POST /openresty/build)
func (s *OpenRestyService) POSTBuild(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/openresty/build", body, out)
}

// POSTFile — Update OpenResty conf by upload file (POST /openresty/file)
func (s *OpenRestyService) POSTFile(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/openresty/file", body, out)
}

// GETHttps — Get default HTTPs status (GET /openresty/https)
func (s *OpenRestyService) GETHttps(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/openresty/https", out)
}

// POSTHttps — Operate default HTTPs (POST /openresty/https)
func (s *OpenRestyService) POSTHttps(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/openresty/https", body, out)
}

// GETModules — Get OpenResty modules (GET /openresty/modules)
func (s *OpenRestyService) GETModules(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/openresty/modules", out)
}

// POSTModulesUpdate — Update OpenResty module (POST /openresty/modules/update)
func (s *OpenRestyService) POSTModulesUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/openresty/modules/update", body, out)
}

// POSTScope — Load partial OpenResty conf (POST /openresty/scope)
func (s *OpenRestyService) POSTScope(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/openresty/scope", body, out)
}

// GETStatus — Load OpenResty status info (GET /openresty/status)
func (s *OpenRestyService) GETStatus(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/openresty/status", out)
}

// POSTUpdate — Update OpenResty conf (POST /openresty/update)
func (s *OpenRestyService) POSTUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/openresty/update", body, out)
}

// POSTListening — Get Listening Process (POST /process/listening)
func (s *ProcessService) POSTListening(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/process/listening", body, out)
}

// POSTStop — Stop Process (POST /process/stop)
func (s *ProcessService) POSTStop(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/process/stop", body, out)
}

// GETWs — Process ws (GET /process/ws)
func (s *ProcessService) GETWs(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/process/ws", out)
}

// GETProcess — Get Process Info By PID (GET /process/{pid})
func (s *ProcessService) GETProcess(ctx context.Context, pid string, body any, out any) error {
	return s.Get(ctx, fmt.Sprintf("/process/%s", pid), out)
}

// POSTRuntimes — Create runtime (POST /runtimes)
func (s *RuntimeService) POSTRuntimes(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes", body, out)
}

// GETid — Get runtime (GET /runtimes/:id)
func (s *RuntimeService) GETid(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/runtimes/:id", out)
}

// POSTDel — Delete runtime (POST /runtimes/del)
func (s *RuntimeService) POSTDel(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/del", body, out)
}

// GETInstalledDeleteCheckid — Delete runtime (GET /runtimes/installed/delete/check/:id)
func (s *RuntimeService) GETInstalledDeleteCheckid(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/runtimes/installed/delete/check/:id", out)
}

// POSTNodeModules — Get Node modules (POST /runtimes/node/modules)
func (s *RuntimeService) POSTNodeModules(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/node/modules", body, out)
}

// POSTNodeModulesOperate — Operate Node modules (POST /runtimes/node/modules/operate)
func (s *RuntimeService) POSTNodeModulesOperate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/node/modules/operate", body, out)
}

// POSTNodePackage — Get Node package scripts (POST /runtimes/node/package)
func (s *RuntimeService) POSTNodePackage(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/node/package", body, out)
}

// POSTOperate — Operate runtime (POST /runtimes/operate)
func (s *RuntimeService) POSTOperate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/operate", body, out)
}

// GETPhpidExtensions — Get php runtime extension (GET /runtimes/php/:id/extensions)
func (s *RuntimeService) GETPhpidExtensions(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/runtimes/php/:id/extensions", out)
}

// POSTPhpConfig — Update runtime php conf (POST /runtimes/php/config)
func (s *RuntimeService) POSTPhpConfig(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/php/config", body, out)
}

// GETPhpConfigid — Load php runtime conf (GET /runtimes/php/config/:id)
func (s *RuntimeService) GETPhpConfigid(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/runtimes/php/config/:id", out)
}

// GETPhpContainerid — Get PHP container config (GET /runtimes/php/container/:id)
func (s *RuntimeService) GETPhpContainerid(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/runtimes/php/container/:id", out)
}

// POSTPhpContainerUpdate — Update PHP container config (POST /runtimes/php/container/update)
func (s *RuntimeService) POSTPhpContainerUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/php/container/update", body, out)
}

// POSTPhpExtensions — Create Extensions (POST /runtimes/php/extensions)
func (s *RuntimeService) POSTPhpExtensions(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/php/extensions", body, out)
}

// POSTPhpExtensionsDel — Delete Extensions (POST /runtimes/php/extensions/del)
func (s *RuntimeService) POSTPhpExtensionsDel(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/php/extensions/del", body, out)
}

// POSTPhpExtensionsInstall — Install php extension (POST /runtimes/php/extensions/install)
func (s *RuntimeService) POSTPhpExtensionsInstall(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/php/extensions/install", body, out)
}

// POSTPhpExtensionsSearch — Page Extensions (POST /runtimes/php/extensions/search)
func (s *RuntimeService) POSTPhpExtensionsSearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/php/extensions/search", body, out)
}

// POSTPhpExtensionsUninstall — UnInstall php extension (POST /runtimes/php/extensions/uninstall)
func (s *RuntimeService) POSTPhpExtensionsUninstall(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/php/extensions/uninstall", body, out)
}

// POSTPhpExtensionsUpdate — Update Extensions (POST /runtimes/php/extensions/update)
func (s *RuntimeService) POSTPhpExtensionsUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/php/extensions/update", body, out)
}

// POSTPhpFile — Get php conf file (POST /runtimes/php/file)
func (s *RuntimeService) POSTPhpFile(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/php/file", body, out)
}

// POSTPhpFpmConfig — Update fpm config (POST /runtimes/php/fpm/config)
func (s *RuntimeService) POSTPhpFpmConfig(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/php/fpm/config", body, out)
}

// GETPhpFpmConfigid — Get fpm config (GET /runtimes/php/fpm/config/:id)
func (s *RuntimeService) GETPhpFpmConfigid(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/runtimes/php/fpm/config/:id", out)
}

// GETPhpFpmStatusid — Get PHP runtime status (GET /runtimes/php/fpm/status/:id)
func (s *RuntimeService) GETPhpFpmStatusid(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/runtimes/php/fpm/status/:id", out)
}

// POSTPhpUpdate — Update php conf file (POST /runtimes/php/update)
func (s *RuntimeService) POSTPhpUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/php/update", body, out)
}

// POSTRemark — Update runtime remark (POST /runtimes/remark)
func (s *RuntimeService) POSTRemark(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/remark", body, out)
}

// POSTSearch — List runtimes (POST /runtimes/search)
func (s *RuntimeService) POSTSearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/search", body, out)
}

// POSTSupervisorProcess — Operate supervisor process (POST /runtimes/supervisor/process)
func (s *RuntimeService) POSTSupervisorProcess(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/supervisor/process", body, out)
}

// GETSupervisorProcessid — Get supervisor process (GET /runtimes/supervisor/process/:id)
func (s *RuntimeService) GETSupervisorProcessid(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/runtimes/supervisor/process/:id", out)
}

// POSTSupervisorProcessFile — Operate supervisor process file (POST /runtimes/supervisor/process/file)
func (s *RuntimeService) POSTSupervisorProcessFile(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/supervisor/process/file", body, out)
}

// POSTSync — Sync runtime status (POST /runtimes/sync)
func (s *RuntimeService) POSTSync(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/sync", body, out)
}

// POSTUpdate — Update runtime (POST /runtimes/update)
func (s *RuntimeService) POSTUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/runtimes/update", body, out)
}

// GETid — Search website by id (GET /websites/:id)
func (s *WebsiteService) GETid(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/websites/:id", out)
}

// GETidConfigtype — Search website nginx by id (GET /websites/:id/config/:type)
func (s *WebsiteService) GETidConfigtype(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/websites/:id/config/:type", out)
}

// GETidHttps — Load https conf (GET /websites/:id/https)
func (s *WebsiteService) GETidHttps(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/websites/:id/https", out)
}

// POSTidHttps — Update https conf (POST /websites/:id/https)
func (s *WebsiteService) POSTidHttps(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/:id/https", body, out)
}

// POSTAuths — Get AuthBasic conf (POST /websites/auths)
func (s *WebsiteService) POSTAuths(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/auths", body, out)
}

// POSTAuthsPath — Get AuthBasic conf (POST /websites/auths/path)
func (s *WebsiteService) POSTAuthsPath(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/auths/path", body, out)
}

// POSTAuthsPathUpdate — Get AuthBasic conf (POST /websites/auths/path/update)
func (s *WebsiteService) POSTAuthsPathUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/auths/path/update", body, out)
}

// POSTAuthsUpdate — Get AuthBasic conf (POST /websites/auths/update)
func (s *WebsiteService) POSTAuthsUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/auths/update", body, out)
}

// POSTBatchGroup — Batch set website group (POST /websites/batch/group)
func (s *WebsiteService) POSTBatchGroup(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/batch/group", body, out)
}

// POSTBatchOperate — Batch operate websites (POST /websites/batch/operate)
func (s *WebsiteService) POSTBatchOperate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/batch/operate", body, out)
}

// POSTBatchSsl — Batch set HTTPS for websites (POST /websites/batch/ssl)
func (s *WebsiteService) POSTBatchSsl(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/batch/ssl", body, out)
}

// POSTCaDownload — Download CA file (POST /websites/ca/download)
func (s *WebsiteService) POSTCaDownload(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/ca/download", body, out)
}

// POSTCaObtain — Obtain SSL (POST /websites/ca/obtain)
func (s *WebsiteService) POSTCaObtain(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/ca/obtain", body, out)
}

// POSTCaRenew — Obtain SSL (POST /websites/ca/renew)
func (s *WebsiteService) POSTCaRenew(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/ca/renew", body, out)
}

// GETCa — Get website ca (GET /websites/ca/{id})
func (s *WebsiteService) GETCa(ctx context.Context, id string, body any, out any) error {
	return s.Get(ctx, fmt.Sprintf("/websites/ca/%s", id), out)
}

// POSTCheck — Check before create website (POST /websites/check)
func (s *WebsiteService) POSTCheck(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/check", body, out)
}

// POSTConfig — Load nginx conf (POST /websites/config)
func (s *WebsiteService) POSTConfig(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/config", body, out)
}

// POSTConfigUpdate — Update nginx conf (POST /websites/config/update)
func (s *WebsiteService) POSTConfigUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/config/update", body, out)
}

// POSTCorsUpdate — Update CORS Config (POST /websites/cors/update)
func (s *WebsiteService) POSTCorsUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/cors/update", body, out)
}

// GETCors — Get CORS Config (GET /websites/cors/{id})
func (s *WebsiteService) GETCors(ctx context.Context, id string, body any, out any) error {
	return s.Get(ctx, fmt.Sprintf("/websites/cors/%s", id), out)
}

// POSTCrosssite — Operate Cross Site Access (POST /websites/crosssite)
func (s *WebsiteService) POSTCrosssite(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/crosssite", body, out)
}

// GETDatabases — Get databases (GET /websites/databases)
func (s *WebsiteService) GETDatabases(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/websites/databases", out)
}

// POSTDatabases — Change website database (POST /websites/databases)
func (s *WebsiteService) POSTDatabases(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/databases", body, out)
}

// GETDefaultHtmltype — Get default html (GET /websites/default/html/:type)
func (s *WebsiteService) GETDefaultHtmltype(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/websites/default/html/:type", out)
}

// POSTDefaultHtmlUpdate — Update default html (POST /websites/default/html/update)
func (s *WebsiteService) POSTDefaultHtmlUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/default/html/update", body, out)
}

// POSTDefaultServer — Change default server (POST /websites/default/server)
func (s *WebsiteService) POSTDefaultServer(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/default/server", body, out)
}

// POSTDir — Get website dir (POST /websites/dir)
func (s *WebsiteService) POSTDir(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/dir", body, out)
}

// POSTDirPermission — Update Site Dir permission (POST /websites/dir/permission)
func (s *WebsiteService) POSTDirPermission(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/dir/permission", body, out)
}

// POSTDirUpdate — Update Site Dir (POST /websites/dir/update)
func (s *WebsiteService) POSTDirUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/dir/update", body, out)
}

// GETDomainswebsiteid — Search website domains by websiteId (GET /websites/domains/:websiteId)
func (s *WebsiteService) GETDomainswebsiteid(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/websites/domains/:websiteId", out)
}

// POSTDomainsDel — Delete website domain (POST /websites/domains/del)
func (s *WebsiteService) POSTDomainsDel(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/domains/del", body, out)
}

// POSTDomainsUpdate — Update website domain (POST /websites/domains/update)
func (s *WebsiteService) POSTDomainsUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/domains/update", body, out)
}

// POSTExecComposer — Exec Composer (POST /websites/exec/composer)
func (s *WebsiteService) POSTExecComposer(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/exec/composer", body, out)
}

// POSTGroupChange — Change website group (POST /websites/group/change)
func (s *WebsiteService) POSTGroupChange(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/group/change", body, out)
}

// POSTLbsCreate — Create website upstream (POST /websites/lbs/create)
func (s *WebsiteService) POSTLbsCreate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/lbs/create", body, out)
}

// POSTLbsDel — Delete website upstream (POST /websites/lbs/del)
func (s *WebsiteService) POSTLbsDel(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/lbs/del", body, out)
}

// POSTLbsFile — Update website upstream file (POST /websites/lbs/file)
func (s *WebsiteService) POSTLbsFile(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/lbs/file", body, out)
}

// POSTLbsUpdate — Update website upstream (POST /websites/lbs/update)
func (s *WebsiteService) POSTLbsUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/lbs/update", body, out)
}

// POSTLeech — Get AntiLeech conf (POST /websites/leech)
func (s *WebsiteService) POSTLeech(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/leech", body, out)
}

// POSTLeechUpdate — Update AntiLeech (POST /websites/leech/update)
func (s *WebsiteService) POSTLeechUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/leech/update", body, out)
}

// POSTLogOperate — Operate website log (POST /websites/log/operate)
func (s *WebsiteService) POSTLogOperate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/log/operate", body, out)
}

// POSTLogSearch — Get website log (POST /websites/log/search)
func (s *WebsiteService) POSTLogSearch(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/log/search", body, out)
}

// POSTNginxUpdate — Update website nginx conf (POST /websites/nginx/update)
func (s *WebsiteService) POSTNginxUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/nginx/update", body, out)
}

// POSTOptions — List website names (POST /websites/options)
func (s *WebsiteService) POSTOptions(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/options", body, out)
}

// POSTPhpVersion — Update php version (POST /websites/php/version)
func (s *WebsiteService) POSTPhpVersion(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/php/version", body, out)
}

// POSTProxies — Get proxy conf (POST /websites/proxies)
func (s *WebsiteService) POSTProxies(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/proxies", body, out)
}

// POSTProxiesDelete — Delete proxy config (POST /websites/proxies/delete)
func (s *WebsiteService) POSTProxiesDelete(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/proxies/delete", body, out)
}

// POSTProxiesFile — Update proxy file (POST /websites/proxies/file)
func (s *WebsiteService) POSTProxiesFile(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/proxies/file", body, out)
}

// POSTProxiesStatus — Update proxy config status (POST /websites/proxies/status)
func (s *WebsiteService) POSTProxiesStatus(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/proxies/status", body, out)
}

// POSTProxiesUpdate — Update proxy conf (POST /websites/proxies/update)
func (s *WebsiteService) POSTProxiesUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/proxies/update", body, out)
}

// POSTProxyClear — Clear Website proxy cache (POST /websites/proxy/clear)
func (s *WebsiteService) POSTProxyClear(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/proxy/clear", body, out)
}

// POSTProxyConfig — update website proxy cache config (POST /websites/proxy/config)
func (s *WebsiteService) POSTProxyConfig(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/proxy/config", body, out)
}

// GETProxyConfig — Get website proxy cache config (GET /websites/proxy/config/{id})
func (s *WebsiteService) GETProxyConfig(ctx context.Context, id string, body any, out any) error {
	return s.Get(ctx, fmt.Sprintf("/websites/proxy/config/%s", id), out)
}

// POSTRealipConfig — Set Real IP (POST /websites/realip/config)
func (s *WebsiteService) POSTRealipConfig(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/realip/config", body, out)
}

// GETRealipConfig — Get Real IP Config (GET /websites/realip/config/{id})
func (s *WebsiteService) GETRealipConfig(ctx context.Context, id string, body any, out any) error {
	return s.Get(ctx, fmt.Sprintf("/websites/realip/config/%s", id), out)
}

// POSTRedirect — Get redirect conf (POST /websites/redirect)
func (s *WebsiteService) POSTRedirect(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/redirect", body, out)
}

// POSTRedirectFile — Update redirect file (POST /websites/redirect/file)
func (s *WebsiteService) POSTRedirectFile(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/redirect/file", body, out)
}

// POSTRedirectUpdate — Update redirect conf (POST /websites/redirect/update)
func (s *WebsiteService) POSTRedirectUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/redirect/update", body, out)
}

// GETResource — Get website resource (GET /websites/resource/{id})
func (s *WebsiteService) GETResource(ctx context.Context, id string, body any, out any) error {
	return s.Get(ctx, fmt.Sprintf("/websites/resource/%s", id), out)
}

// POSTRewrite — Get rewrite conf (POST /websites/rewrite)
func (s *WebsiteService) POSTRewrite(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/rewrite", body, out)
}

// GETRewriteCustom — List custom rewrite (GET /websites/rewrite/custom)
func (s *WebsiteService) GETRewriteCustom(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/websites/rewrite/custom", out)
}

// POSTRewriteCustom — Operate custom rewrite (POST /websites/rewrite/custom)
func (s *WebsiteService) POSTRewriteCustom(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/rewrite/custom", body, out)
}

// POSTRewriteUpdate — Update rewrite conf (POST /websites/rewrite/update)
func (s *WebsiteService) POSTRewriteUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/rewrite/update", body, out)
}

// GETSslid — Search website ssl by id (GET /websites/ssl/:id)
func (s *WebsiteService) GETSslid(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/websites/ssl/:id", out)
}

// POSTSslDownload — Download SSL  file (POST /websites/ssl/download)
func (s *WebsiteService) POSTSslDownload(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/ssl/download", body, out)
}

// POSTSslImport — Import master SSL (POST /websites/ssl/import)
func (s *WebsiteService) POSTSslImport(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/ssl/import", body, out)
}

// POSTSslList — List website ssl (POST /websites/ssl/list)
func (s *WebsiteService) POSTSslList(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/ssl/list", body, out)
}

// POSTSslObtain — Apply  ssl (POST /websites/ssl/obtain)
func (s *WebsiteService) POSTSslObtain(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/ssl/obtain", body, out)
}

// POSTSslPush — Push ssl to nodes (POST /websites/ssl/push)
func (s *WebsiteService) POSTSslPush(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/ssl/push", body, out)
}

// POSTSslResolve — Resolve website ssl (POST /websites/ssl/resolve)
func (s *WebsiteService) POSTSslResolve(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/ssl/resolve", body, out)
}

// POSTSslUpload — Upload ssl (POST /websites/ssl/upload)
func (s *WebsiteService) POSTSslUpload(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/ssl/upload", body, out)
}

// POSTSslUploadFile — Upload SSL file (POST /websites/ssl/upload/file)
func (s *WebsiteService) POSTSslUploadFile(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/ssl/upload/file", body, out)
}

// GETSslWebsitewebsiteid — Search website ssl by website id (GET /websites/ssl/website/:websiteId)
func (s *WebsiteService) GETSslWebsitewebsiteid(ctx context.Context, body any, out any) error {
	return s.Get(ctx, "/websites/ssl/website/:websiteId", out)
}

// POSTStreamUpdate — Update Stream Config (POST /websites/stream/update)
func (s *WebsiteService) POSTStreamUpdate(ctx context.Context, body any, out any) error {
	return s.Post(ctx, "/websites/stream/update", body, out)
}

// GETLbs — Get website upstreams (GET /websites/{id}/lbs)
func (s *WebsiteService) GETLbs(ctx context.Context, id string, body any, out any) error {
	return s.Get(ctx, fmt.Sprintf("/websites/%s/lbs", id), out)
}
