// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel

import (
	"context"
	"fmt"
)

// POSTFiles — Create file (POST /files)
func (s *FileService) POSTFiles(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files", body)
}

// POSTAisearch — File search: content grep + optional AI summary (POST /files/ai-search)
func (s *FileService) POSTAisearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/ai-search", body)
}

// POSTBatchCheck — Batch check file exist (POST /files/batch/check)
func (s *FileService) POSTBatchCheck(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/batch/check", body)
}

// POSTBatchDel — Batch delete file (POST /files/batch/del)
func (s *FileService) POSTBatchDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/batch/del", body)
}

// POSTBatchRole — Batch change file mode and owner (POST /files/batch/role)
func (s *FileService) POSTBatchRole(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/batch/role", body)
}

// POSTCheck — Check file exist (POST /files/check)
func (s *FileService) POSTCheck(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/check", body)
}

// POSTChunkdownload — Chunk Download file (POST /files/chunkdownload)
func (s *FileService) POSTChunkdownload(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/chunkdownload", body)
}

// POSTChunkupload — ChunkUpload file (POST /files/chunkupload)
func (s *FileService) POSTChunkupload(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/chunkupload", body)
}

// POSTCompress — Compress file (POST /files/compress)
func (s *FileService) POSTCompress(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/compress", body)
}

// POSTCompressStop — Stop compress task (POST /files/compress/stop)
func (s *FileService) POSTCompressStop(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/compress/stop", body)
}

// POSTContent — Load file content (POST /files/content)
func (s *FileService) POSTContent(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/content", body)
}

// POSTConvert — Convert file (POST /files/convert)
func (s *FileService) POSTConvert(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/convert", body)
}

// POSTConvertLog — Convert file (POST /files/convert/log)
func (s *FileService) POSTConvertLog(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/convert/log", body)
}

// POSTDecompress — Decompress file (POST /files/decompress)
func (s *FileService) POSTDecompress(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/decompress", body)
}

// POSTDecompressStop — Stop decompress task (POST /files/decompress/stop)
func (s *FileService) POSTDecompressStop(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/decompress/stop", body)
}

// POSTDel — Delete file (POST /files/del)
func (s *FileService) POSTDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/del", body)
}

// POSTDepthSize — Multi file size (POST /files/depth/size)
func (s *FileService) POSTDepthSize(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/depth/size", body)
}

// GETDownload — Download file (GET /files/download)
func (s *FileService) GETDownload(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/files/download")
}

// POSTFavorite — Create favorite (POST /files/favorite)
func (s *FileService) POSTFavorite(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/favorite", body)
}

// POSTFavoriteDel — Delete favorite (POST /files/favorite/del)
func (s *FileService) POSTFavoriteDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/favorite/del", body)
}

// POSTFavoriteSearch — List favorites (POST /files/favorite/search)
func (s *FileService) POSTFavoriteSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/favorite/search", body)
}

// POSTHistoryContent — Load file history content (POST /files/history/content)
func (s *FileService) POSTHistoryContent(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/history/content", body)
}

// POSTHistoryDel — Delete file history record (POST /files/history/del)
func (s *FileService) POSTHistoryDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/history/del", body)
}

// POSTHistoryRestore — Restore file history record (POST /files/history/restore)
func (s *FileService) POSTHistoryRestore(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/history/restore", body)
}

// POSTHistorySearch — Load file history list (POST /files/history/search)
func (s *FileService) POSTHistorySearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/history/search", body)
}

// POSTMode — Change file mode (POST /files/mode)
func (s *FileService) POSTMode(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/mode", body)
}

// POSTMount — system mount (POST /files/mount)
func (s *FileService) POSTMount(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/mount", body)
}

// POSTMove — Move file (POST /files/move)
func (s *FileService) POSTMove(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/move", body)
}

// POSTOwner — Change file owner (POST /files/owner)
func (s *FileService) POSTOwner(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/owner", body)
}

// POSTPreview — Preview file content (POST /files/preview)
func (s *FileService) POSTPreview(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/preview", body)
}

// POSTRead — Read file by Line (POST /files/read/{type})
func (s *FileService) POSTRead(ctx context.Context, typeVal string, body any) (map[string]any, error) {
	return s.postMap(ctx, fmt.Sprintf("/files/read/%s", typeVal), body)
}

// POSTRecycleClear — Clear RecycleBin files (POST /files/recycle/clear)
func (s *FileService) POSTRecycleClear(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/recycle/clear", body)
}

// POSTRecycleReduce — Reduce RecycleBin files (POST /files/recycle/reduce)
func (s *FileService) POSTRecycleReduce(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/recycle/reduce", body)
}

// POSTRecycleSearch — List RecycleBin files (POST /files/recycle/search)
func (s *FileService) POSTRecycleSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/recycle/search", body)
}

// GETRecycleStatus — Get RecycleBin status (GET /files/recycle/status)
func (s *FileService) GETRecycleStatus(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/files/recycle/status")
}

// POSTRemark — Set file remark (POST /files/remark)
func (s *FileService) POSTRemark(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/remark", body)
}

// POSTRemarks — Batch get file remarks (POST /files/remarks)
func (s *FileService) POSTRemarks(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/remarks", body)
}

// POSTRename — Change file name (POST /files/rename)
func (s *FileService) POSTRename(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/rename", body)
}

// POSTSave — Update file content (POST /files/save)
func (s *FileService) POSTSave(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/save", body)
}

// POSTSearch — List files (POST /files/search)
func (s *FileService) POSTSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/search", body)
}

// GETShareCheck — Check file share code (no login) (GET /files/share/check)
func (s *FileService) GETShareCheck(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/files/share/check")
}

// POSTShareCreate — Create temporary file share link (POST /files/share/create)
func (s *FileService) POSTShareCreate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/share/create", body)
}

// POSTShareDel — Delete file share by path (POST /files/share/del)
func (s *FileService) POSTShareDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/share/del", body)
}

// POSTShareDetail — Get file share detail by path (POST /files/share/detail)
func (s *FileService) POSTShareDetail(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/share/detail", body)
}

// GETShareDownload — Download file by share code (no login) (GET /files/share/download)
func (s *FileService) GETShareDownload(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/files/share/download")
}

// GETShareInfo — Get file share detail by code (no login) (GET /files/share/info)
func (s *FileService) GETShareInfo(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/files/share/info")
}

// GETShareQrcode — Get file share QR code image (GET /files/share/qrcode)
func (s *FileService) GETShareQrcode(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/files/share/qrcode")
}

// POSTShareSearch — List file shares (POST /files/share/search)
func (s *FileService) POSTShareSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/share/search", body)
}

// POSTSize — Load file size (POST /files/size)
func (s *FileService) POSTSize(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/size", body)
}

// POSTTree — Load files tree (POST /files/tree)
func (s *FileService) POSTTree(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/tree", body)
}

// POSTUpload — Upload file (POST /files/upload)
func (s *FileService) POSTUpload(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/upload", body)
}

// POSTUploadSearch — Page file (POST /files/upload/search)
func (s *FileService) POSTUploadSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/upload/search", body)
}

// POSTUserGroup — system user and group (POST /files/user/group)
func (s *FileService) POSTUserGroup(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/user/group", body)
}

// POSTWget — Wget file (POST /files/wget)
func (s *FileService) POSTWget(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/wget", body)
}

// GETWgetProcess — Wget process (GET /files/wget/process)
func (s *FileService) GETWgetProcess(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/files/wget/process")
}

// GETWgetProcessKeys — Process keys (GET /files/wget/process/keys)
func (s *FileService) GETWgetProcessKeys(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/files/wget/process/keys")
}

// POSTWgetStop — Stop wget file download (POST /files/wget/stop)
func (s *FileService) POSTWgetStop(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/files/wget/stop", body)
}
