// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel

import (
	"context"
)

// GETAppLauncher — Load app launcher (GET /dashboard/app/launcher)
func (s *DashboardService) GETAppLauncher(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/dashboard/app/launcher")
}

// POSTAppLauncherOption — Load app launcher options (POST /dashboard/app/launcher/option)
func (s *DashboardService) POSTAppLauncherOption(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/dashboard/app/launcher/option", body)
}

// POSTAppLauncherShow — Update app Launcher (POST /dashboard/app/launcher/show)
func (s *DashboardService) POSTAppLauncherShow(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/dashboard/app/launcher/show", body)
}

// GETBaseiooptionnetoption — Load dashboard base info (GET /dashboard/base/:ioOption/:netOption)
func (s *DashboardService) GETBaseiooptionnetoption(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/dashboard/base/:ioOption/:netOption")
}

// GETBaseOs — Load os info (GET /dashboard/base/os)
func (s *DashboardService) GETBaseOs(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/dashboard/base/os")
}

// GETCurrentiooptionnetoption — Load dashboard current info (GET /dashboard/current/:ioOption/:netOption)
func (s *DashboardService) GETCurrentiooptionnetoption(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/dashboard/current/:ioOption/:netOption")
}

// GETCurrentNode — Load dashboard current info for node (GET /dashboard/current/node)
func (s *DashboardService) GETCurrentNode(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/dashboard/current/node")
}

// GETCurrentTopCpu — Load top cpu processes (GET /dashboard/current/top/cpu)
func (s *DashboardService) GETCurrentTopCpu(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/dashboard/current/top/cpu")
}

// GETCurrentTopMem — Load top memory processes (GET /dashboard/current/top/mem)
func (s *DashboardService) GETCurrentTopMem(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/dashboard/current/top/mem")
}

// POSTQuickChange — Update quick jump (POST /dashboard/quick/change)
func (s *DashboardService) POSTQuickChange(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/dashboard/quick/change", body)
}

// GETQuickOption — Load quick jump options (GET /dashboard/quick/option)
func (s *DashboardService) GETQuickOption(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/dashboard/quick/option")
}

// POSTSystemRestartoperation — System restart (POST /dashboard/system/restart/:operation)
func (s *DashboardService) POSTSystemRestartoperation(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/dashboard/system/restart/:operation", body)
}
