// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel

import (
	"context"
)

// GETSystemFiles — Load system log files (GET /logs/system/files)
func (s *LogsService) GETSystemFiles(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/logs/system/files")
}

// POSTSystemRead — Read host logs (POST /logs/system/read)
func (s *LogsService) POSTSystemRead(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/logs/system/read", body)
}

// GETSystemServices — List running host services (GET /logs/system/services)
func (s *LogsService) GETSystemServices(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/logs/system/services")
}

// GETSystemStatus — Get host system log status (GET /logs/system/status)
func (s *LogsService) GETSystemStatus(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/logs/system/status")
}

// GETTasksExecutingCount — Get the number of executing tasks (GET /logs/tasks/executing/count)
func (s *LogsService) GETTasksExecutingCount(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/logs/tasks/executing/count")
}

// POSTTasksRead — Read task log by Line (POST /logs/tasks/read)
func (s *LogsService) POSTTasksRead(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/logs/tasks/read", body)
}

// POSTTasksSearch — Page task logs (POST /logs/tasks/search)
func (s *LogsService) POSTTasksSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/logs/tasks/search", body)
}
