// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel
import (
	"context"
)

// POSTContainers — Create container (POST /containers)
func (s *ContainerService) POSTContainers(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers", body)
}

// POSTCleanLog — Clean container log (POST /containers/clean/log)
func (s *ContainerService) POSTCleanLog(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/clean/log", body)
}

// POSTCommit — Commit Container (POST /containers/commit)
func (s *ContainerService) POSTCommit(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/commit", body)
}

// POSTCompose — Create compose (POST /containers/compose)
func (s *ContainerService) POSTCompose(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/compose", body)
}

// POSTComposeCleanLog — Clean compose log (POST /containers/compose/clean/log)
func (s *ContainerService) POSTComposeCleanLog(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/compose/clean/log", body)
}

// POSTComposeEnv — Load compose environment variables (POST /containers/compose/env)
func (s *ContainerService) POSTComposeEnv(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/compose/env", body)
}

// POSTComposeOperate — Operate compose (POST /containers/compose/operate)
func (s *ContainerService) POSTComposeOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/compose/operate", body)
}

// POSTComposeSearch — Page composes (POST /containers/compose/search)
func (s *ContainerService) POSTComposeSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/compose/search", body)
}

// POSTComposeTest — Test compose (POST /containers/compose/test)
func (s *ContainerService) POSTComposeTest(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/compose/test", body)
}

// POSTComposeUpdate — Update compose (POST /containers/compose/update)
func (s *ContainerService) POSTComposeUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/compose/update", body)
}

// GETDaemonjson — Load docker daemon.json (GET /containers/daemonjson)
func (s *ContainerService) GETDaemonjson(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/containers/daemonjson")
}

// GETDaemonjsonFile — Load docker daemon.json (GET /containers/daemonjson/file)
func (s *ContainerService) GETDaemonjsonFile(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/containers/daemonjson/file")
}

// POSTDaemonjsonUpdate — Update docker daemon.json (POST /containers/daemonjson/update)
func (s *ContainerService) POSTDaemonjsonUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/daemonjson/update", body)
}

// POSTDaemonjsonUpdateByfile — Update docker daemon.json by upload file (POST /containers/daemonjson/update/byfile)
func (s *ContainerService) POSTDaemonjsonUpdateByfile(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/daemonjson/update/byfile", body)
}

// POSTDockerOperate — Operate docker (POST /containers/docker/operate)
func (s *ContainerService) POSTDockerOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/docker/operate", body)
}

// GETDockerStatus — Load docker status (GET /containers/docker/status)
func (s *ContainerService) GETDockerStatus(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/containers/docker/status")
}

// POSTDownloadLog — Download container logs (POST /containers/download/log)
func (s *ContainerService) POSTDownloadLog(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/download/log", body)
}

// POSTFilesContent — Get container file content (POST /containers/files/content)
func (s *ContainerService) POSTFilesContent(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/files/content", body)
}

// POSTFilesDel — Delete container file (POST /containers/files/del)
func (s *ContainerService) POSTFilesDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/files/del", body)
}

// POSTFilesDownload — Download container file (POST /containers/files/download)
func (s *ContainerService) POSTFilesDownload(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/files/download", body)
}

// POSTFilesSearch — List container files (POST /containers/files/search)
func (s *ContainerService) POSTFilesSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/files/search", body)
}

// POSTFilesSize — Get container file size (POST /containers/files/size)
func (s *ContainerService) POSTFilesSize(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/files/size", body)
}

// POSTFilesUpload — Upload container file (POST /containers/files/upload)
func (s *ContainerService) POSTFilesUpload(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/files/upload", body)
}

// GETImage — load images options (GET /containers/image)
func (s *ContainerService) GETImage(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/containers/image")
}

// GETImageAll — List all images (GET /containers/image/all)
func (s *ContainerService) GETImageAll(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/containers/image/all")
}

// POSTImageBuild — Build image (POST /containers/image/build)
func (s *ContainerService) POSTImageBuild(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/image/build", body)
}

// POSTImageLoad — Load image (POST /containers/image/load)
func (s *ContainerService) POSTImageLoad(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/image/load", body)
}

// POSTImagePull — Pull image (POST /containers/image/pull)
func (s *ContainerService) POSTImagePull(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/image/pull", body)
}

// POSTImagePush — Push image (POST /containers/image/push)
func (s *ContainerService) POSTImagePush(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/image/push", body)
}

// POSTImageRemove — Delete image (POST /containers/image/remove)
func (s *ContainerService) POSTImageRemove(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/image/remove", body)
}

// POSTImageSave — Save image (POST /containers/image/save)
func (s *ContainerService) POSTImageSave(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/image/save", body)
}

// POSTImageSearch — Page images (POST /containers/image/search)
func (s *ContainerService) POSTImageSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/image/search", body)
}

// POSTImageTag — Tag image (POST /containers/image/tag)
func (s *ContainerService) POSTImageTag(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/image/tag", body)
}

// POSTInfo — Load container info (POST /containers/info)
func (s *ContainerService) POSTInfo(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/info", body)
}

// POSTInspect — Container inspect (POST /containers/inspect)
func (s *ContainerService) POSTInspect(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/inspect", body)
}

// POSTIpv6optionUpdate — Update docker daemon.json ipv6 option (POST /containers/ipv6option/update)
func (s *ContainerService) POSTIpv6optionUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/ipv6option/update", body)
}

// POSTItemStats — Load container stats size (POST /containers/item/stats)
func (s *ContainerService) POSTItemStats(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/item/stats", body)
}

// GETLimit — Load container limits (GET /containers/limit)
func (s *ContainerService) GETLimit(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/containers/limit")
}

// POSTList — List containers (POST /containers/list)
func (s *ContainerService) POSTList(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/list", body)
}

// POSTListByimage — List containers by image (POST /containers/list/byimage)
func (s *ContainerService) POSTListByimage(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/list/byimage", body)
}

// GETListStats — Load container stats (GET /containers/list/stats)
func (s *ContainerService) GETListStats(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/containers/list/stats")
}

// POSTLogoptionUpdate — Update docker daemon.json log option (POST /containers/logoption/update)
func (s *ContainerService) POSTLogoptionUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/logoption/update", body)
}

// GETNetwork — List networks (GET /containers/network)
func (s *ContainerService) GETNetwork(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/containers/network")
}

// POSTNetwork — Create network (POST /containers/network)
func (s *ContainerService) POSTNetwork(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/network", body)
}

// POSTNetworkDel — Delete network (POST /containers/network/del)
func (s *ContainerService) POSTNetworkDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/network/del", body)
}

// POSTNetworkSearch — Page networks (POST /containers/network/search)
func (s *ContainerService) POSTNetworkSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/network/search", body)
}

// POSTOperate — Operate Container (POST /containers/operate)
func (s *ContainerService) POSTOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/operate", body)
}

// POSTPrune — Clean container (POST /containers/prune)
func (s *ContainerService) POSTPrune(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/prune", body)
}

// POSTRename — Rename Container (POST /containers/rename)
func (s *ContainerService) POSTRename(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/rename", body)
}

// GETRepo — List image repos (GET /containers/repo)
func (s *ContainerService) GETRepo(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/containers/repo")
}

// POSTRepo — Create image repo (POST /containers/repo)
func (s *ContainerService) POSTRepo(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/repo", body)
}

// POSTRepoDel — Delete image repo (POST /containers/repo/del)
func (s *ContainerService) POSTRepoDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/repo/del", body)
}

// POSTRepoSearch — Page image repos (POST /containers/repo/search)
func (s *ContainerService) POSTRepoSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/repo/search", body)
}

// POSTRepoStatus — Load repo status (POST /containers/repo/status)
func (s *ContainerService) POSTRepoStatus(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/repo/status", body)
}

// POSTRepoUpdate — Update image repo (POST /containers/repo/update)
func (s *ContainerService) POSTRepoUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/repo/update", body)
}

// POSTSearch — Page containers (POST /containers/search)
func (s *ContainerService) POSTSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/search", body)
}

// GETSearchLog — Container logs (GET /containers/search/log)
func (s *ContainerService) GETSearchLog(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/containers/search/log")
}

// GETStatsid — Container stats (GET /containers/stats/:id)
func (s *ContainerService) GETStatsid(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/containers/stats/:id")
}

// GETStatus — Load containers status (GET /containers/status)
func (s *ContainerService) GETStatus(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/containers/status")
}

// GETTemplate — List compose templates (GET /containers/template)
func (s *ContainerService) GETTemplate(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/containers/template")
}

// POSTTemplate — Create compose template (POST /containers/template)
func (s *ContainerService) POSTTemplate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/template", body)
}

// POSTTemplateBatch — Bacth compose template (POST /containers/template/batch)
func (s *ContainerService) POSTTemplateBatch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/template/batch", body)
}

// POSTTemplateDel — Delete compose template (POST /containers/template/del)
func (s *ContainerService) POSTTemplateDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/template/del", body)
}

// POSTTemplateSearch — Page compose templates (POST /containers/template/search)
func (s *ContainerService) POSTTemplateSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/template/search", body)
}

// POSTTemplateUpdate — Update compose template (POST /containers/template/update)
func (s *ContainerService) POSTTemplateUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/template/update", body)
}

// POSTUpdate — Update container (POST /containers/update)
func (s *ContainerService) POSTUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/update", body)
}

// POSTUpgrade — Upgrade container (POST /containers/upgrade)
func (s *ContainerService) POSTUpgrade(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/upgrade", body)
}

// POSTUsers — Load container users (POST /containers/users)
func (s *ContainerService) POSTUsers(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/users", body)
}

// GETVolume — List volumes (GET /containers/volume)
func (s *ContainerService) GETVolume(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/containers/volume")
}

// POSTVolume — Create volume (POST /containers/volume)
func (s *ContainerService) POSTVolume(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/volume", body)
}

// POSTVolumeDel — Delete volume (POST /containers/volume/del)
func (s *ContainerService) POSTVolumeDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/volume/del", body)
}

// POSTVolumeSearch — Page volumes (POST /containers/volume/search)
func (s *ContainerService) POSTVolumeSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/containers/volume/search", body)
}

