// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel

import (
	"context"
	"fmt"
)

// POSTWebsites — Create website (POST /websites)
func (s *WebsiteService) POSTWebsites(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites", body)
}

// GETid — Search website by id (GET /websites/:id)
func (s *WebsiteService) GETid(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/websites/:id")
}

// GETidConfigtype — Search website nginx by id (GET /websites/:id/config/:type)
func (s *WebsiteService) GETidConfigtype(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/websites/:id/config/:type")
}

// GETidHttps — Load https conf (GET /websites/:id/https)
func (s *WebsiteService) GETidHttps(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/websites/:id/https")
}

// POSTidHttps — Update https conf (POST /websites/:id/https)
func (s *WebsiteService) POSTidHttps(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/:id/https", body)
}

// POSTAcme — Create website acme account (POST /websites/acme)
func (s *WebsiteService) POSTAcme(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/acme", body)
}

// POSTAcmeDel — Delete website acme account (POST /websites/acme/del)
func (s *WebsiteService) POSTAcmeDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/acme/del", body)
}

// POSTAcmeSearch — Page website acme accounts (POST /websites/acme/search)
func (s *WebsiteService) POSTAcmeSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/acme/search", body)
}

// POSTAcmeUpdate — Update website acme account (POST /websites/acme/update)
func (s *WebsiteService) POSTAcmeUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/acme/update", body)
}

// POSTAuths — Get AuthBasic conf (POST /websites/auths)
func (s *WebsiteService) POSTAuths(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/auths", body)
}

// POSTAuthsPath — Get AuthBasic conf (POST /websites/auths/path)
func (s *WebsiteService) POSTAuthsPath(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/auths/path", body)
}

// POSTAuthsPathUpdate — Get AuthBasic conf (POST /websites/auths/path/update)
func (s *WebsiteService) POSTAuthsPathUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/auths/path/update", body)
}

// POSTAuthsUpdate — Get AuthBasic conf (POST /websites/auths/update)
func (s *WebsiteService) POSTAuthsUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/auths/update", body)
}

// POSTBatchGroup — Batch set website group (POST /websites/batch/group)
func (s *WebsiteService) POSTBatchGroup(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/batch/group", body)
}

// POSTBatchOperate — Batch operate websites (POST /websites/batch/operate)
func (s *WebsiteService) POSTBatchOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/batch/operate", body)
}

// POSTBatchSsl — Batch set HTTPS for websites (POST /websites/batch/ssl)
func (s *WebsiteService) POSTBatchSsl(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/batch/ssl", body)
}

// POSTCa — Create website ca (POST /websites/ca)
func (s *WebsiteService) POSTCa(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ca", body)
}

// POSTCaDel — Delete website ca (POST /websites/ca/del)
func (s *WebsiteService) POSTCaDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ca/del", body)
}

// POSTCaDownload — Download CA file (POST /websites/ca/download)
func (s *WebsiteService) POSTCaDownload(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ca/download", body)
}

// POSTCaObtain — Obtain SSL (POST /websites/ca/obtain)
func (s *WebsiteService) POSTCaObtain(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ca/obtain", body)
}

// POSTCaRenew — Obtain SSL (POST /websites/ca/renew)
func (s *WebsiteService) POSTCaRenew(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ca/renew", body)
}

// POSTCaSearch — Page website ca (POST /websites/ca/search)
func (s *WebsiteService) POSTCaSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ca/search", body)
}

// GETCa — Get website ca (GET /websites/ca/{id})
func (s *WebsiteService) GETCa(ctx context.Context, id string) (map[string]any, error) {
	return s.getMap(ctx, fmt.Sprintf("/websites/ca/%s", id))
}

// POSTCheck — Check before create website (POST /websites/check)
func (s *WebsiteService) POSTCheck(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/check", body)
}

// POSTConfig — Load nginx conf (POST /websites/config)
func (s *WebsiteService) POSTConfig(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/config", body)
}

// POSTConfigUpdate — Update nginx conf (POST /websites/config/update)
func (s *WebsiteService) POSTConfigUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/config/update", body)
}

// POSTCorsUpdate — Update CORS Config (POST /websites/cors/update)
func (s *WebsiteService) POSTCorsUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/cors/update", body)
}

// GETCors — Get CORS Config (GET /websites/cors/{id})
func (s *WebsiteService) GETCors(ctx context.Context, id string) (map[string]any, error) {
	return s.getMap(ctx, fmt.Sprintf("/websites/cors/%s", id))
}

// POSTCrosssite — Operate Cross Site Access (POST /websites/crosssite)
func (s *WebsiteService) POSTCrosssite(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/crosssite", body)
}

// GETDatabases — Get databases (GET /websites/databases)
func (s *WebsiteService) GETDatabases(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/websites/databases")
}

// POSTDatabases — Change website database (POST /websites/databases)
func (s *WebsiteService) POSTDatabases(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/databases", body)
}

// GETDefaultHtmltype — Get default html (GET /websites/default/html/:type)
func (s *WebsiteService) GETDefaultHtmltype(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/websites/default/html/:type")
}

// POSTDefaultHtmlUpdate — Update default html (POST /websites/default/html/update)
func (s *WebsiteService) POSTDefaultHtmlUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/default/html/update", body)
}

// POSTDefaultServer — Change default server (POST /websites/default/server)
func (s *WebsiteService) POSTDefaultServer(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/default/server", body)
}

// POSTDel — Delete website (POST /websites/del)
func (s *WebsiteService) POSTDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/del", body)
}

// POSTDir — Get website dir (POST /websites/dir)
func (s *WebsiteService) POSTDir(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/dir", body)
}

// POSTDirPermission — Update Site Dir permission (POST /websites/dir/permission)
func (s *WebsiteService) POSTDirPermission(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/dir/permission", body)
}

// POSTDirUpdate — Update Site Dir (POST /websites/dir/update)
func (s *WebsiteService) POSTDirUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/dir/update", body)
}

// POSTDns — Create website dns account (POST /websites/dns)
func (s *WebsiteService) POSTDns(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/dns", body)
}

// POSTDnsDel — Delete website dns account (POST /websites/dns/del)
func (s *WebsiteService) POSTDnsDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/dns/del", body)
}

// POSTDnsSearch — Page website dns accounts (POST /websites/dns/search)
func (s *WebsiteService) POSTDnsSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/dns/search", body)
}

// POSTDnsUpdate — Update website dns account (POST /websites/dns/update)
func (s *WebsiteService) POSTDnsUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/dns/update", body)
}

// POSTDomains — Create website domain (POST /websites/domains)
func (s *WebsiteService) POSTDomains(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/domains", body)
}

// GETDomainswebsiteid — Search website domains by websiteId (GET /websites/domains/:websiteId)
func (s *WebsiteService) GETDomainswebsiteid(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/websites/domains/:websiteId")
}

// POSTDomainsDel — Delete website domain (POST /websites/domains/del)
func (s *WebsiteService) POSTDomainsDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/domains/del", body)
}

// POSTDomainsUpdate — Update website domain (POST /websites/domains/update)
func (s *WebsiteService) POSTDomainsUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/domains/update", body)
}

// POSTExecComposer — Exec Composer (POST /websites/exec/composer)
func (s *WebsiteService) POSTExecComposer(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/exec/composer", body)
}

// POSTGroupChange — Change website group (POST /websites/group/change)
func (s *WebsiteService) POSTGroupChange(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/group/change", body)
}

// POSTLbsCreate — Create website upstream (POST /websites/lbs/create)
func (s *WebsiteService) POSTLbsCreate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/lbs/create", body)
}

// POSTLbsDel — Delete website upstream (POST /websites/lbs/del)
func (s *WebsiteService) POSTLbsDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/lbs/del", body)
}

// POSTLbsFile — Update website upstream file (POST /websites/lbs/file)
func (s *WebsiteService) POSTLbsFile(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/lbs/file", body)
}

// POSTLbsUpdate — Update website upstream (POST /websites/lbs/update)
func (s *WebsiteService) POSTLbsUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/lbs/update", body)
}

// POSTLeech — Get AntiLeech conf (POST /websites/leech)
func (s *WebsiteService) POSTLeech(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/leech", body)
}

// POSTLeechUpdate — Update AntiLeech (POST /websites/leech/update)
func (s *WebsiteService) POSTLeechUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/leech/update", body)
}

// GETList — List websites (GET /websites/list)
func (s *WebsiteService) GETList(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/websites/list")
}

// POSTLogOperate — Operate website log (POST /websites/log/operate)
func (s *WebsiteService) POSTLogOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/log/operate", body)
}

// POSTLogSearch — Get website log (POST /websites/log/search)
func (s *WebsiteService) POSTLogSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/log/search", body)
}

// POSTNginxUpdate — Update website nginx conf (POST /websites/nginx/update)
func (s *WebsiteService) POSTNginxUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/nginx/update", body)
}

// POSTOperate — Operate website (POST /websites/operate)
func (s *WebsiteService) POSTOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/operate", body)
}

// POSTOptions — List website names (POST /websites/options)
func (s *WebsiteService) POSTOptions(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/options", body)
}

// POSTPhpVersion — Update php version (POST /websites/php/version)
func (s *WebsiteService) POSTPhpVersion(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/php/version", body)
}

// POSTProxies — Get proxy conf (POST /websites/proxies)
func (s *WebsiteService) POSTProxies(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/proxies", body)
}

// POSTProxiesDelete — Delete proxy config (POST /websites/proxies/delete)
func (s *WebsiteService) POSTProxiesDelete(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/proxies/delete", body)
}

// POSTProxiesFile — Update proxy file (POST /websites/proxies/file)
func (s *WebsiteService) POSTProxiesFile(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/proxies/file", body)
}

// POSTProxiesStatus — Update proxy config status (POST /websites/proxies/status)
func (s *WebsiteService) POSTProxiesStatus(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/proxies/status", body)
}

// POSTProxiesUpdate — Update proxy conf (POST /websites/proxies/update)
func (s *WebsiteService) POSTProxiesUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/proxies/update", body)
}

// POSTProxyClear — Clear Website proxy cache (POST /websites/proxy/clear)
func (s *WebsiteService) POSTProxyClear(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/proxy/clear", body)
}

// POSTProxyConfig — update website proxy cache config (POST /websites/proxy/config)
func (s *WebsiteService) POSTProxyConfig(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/proxy/config", body)
}

// GETProxyConfig — Get website proxy cache config (GET /websites/proxy/config/{id})
func (s *WebsiteService) GETProxyConfig(ctx context.Context, id string) (map[string]any, error) {
	return s.getMap(ctx, fmt.Sprintf("/websites/proxy/config/%s", id))
}

// POSTRealipConfig — Set Real IP (POST /websites/realip/config)
func (s *WebsiteService) POSTRealipConfig(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/realip/config", body)
}

// GETRealipConfig — Get Real IP Config (GET /websites/realip/config/{id})
func (s *WebsiteService) GETRealipConfig(ctx context.Context, id string) (map[string]any, error) {
	return s.getMap(ctx, fmt.Sprintf("/websites/realip/config/%s", id))
}

// POSTRedirect — Get redirect conf (POST /websites/redirect)
func (s *WebsiteService) POSTRedirect(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/redirect", body)
}

// POSTRedirectFile — Update redirect file (POST /websites/redirect/file)
func (s *WebsiteService) POSTRedirectFile(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/redirect/file", body)
}

// POSTRedirectUpdate — Update redirect conf (POST /websites/redirect/update)
func (s *WebsiteService) POSTRedirectUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/redirect/update", body)
}

// GETResource — Get website resource (GET /websites/resource/{id})
func (s *WebsiteService) GETResource(ctx context.Context, id string) (map[string]any, error) {
	return s.getMap(ctx, fmt.Sprintf("/websites/resource/%s", id))
}

// POSTRewrite — Get rewrite conf (POST /websites/rewrite)
func (s *WebsiteService) POSTRewrite(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/rewrite", body)
}

// GETRewriteCustom — List custom rewrite (GET /websites/rewrite/custom)
func (s *WebsiteService) GETRewriteCustom(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/websites/rewrite/custom")
}

// POSTRewriteCustom — Operate custom rewrite (POST /websites/rewrite/custom)
func (s *WebsiteService) POSTRewriteCustom(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/rewrite/custom", body)
}

// POSTRewriteUpdate — Update rewrite conf (POST /websites/rewrite/update)
func (s *WebsiteService) POSTRewriteUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/rewrite/update", body)
}

// POSTSearch — Page websites (POST /websites/search)
func (s *WebsiteService) POSTSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/search", body)
}

// POSTSsl — Create website ssl (POST /websites/ssl)
func (s *WebsiteService) POSTSsl(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ssl", body)
}

// GETSslid — Search website ssl by id (GET /websites/ssl/:id)
func (s *WebsiteService) GETSslid(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/websites/ssl/:id")
}

// POSTSslDel — Delete website ssl (POST /websites/ssl/del)
func (s *WebsiteService) POSTSslDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ssl/del", body)
}

// POSTSslDownload — Download SSL  file (POST /websites/ssl/download)
func (s *WebsiteService) POSTSslDownload(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ssl/download", body)
}

// POSTSslImport — Import master SSL (POST /websites/ssl/import)
func (s *WebsiteService) POSTSslImport(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ssl/import", body)
}

// POSTSslList — List website ssl (POST /websites/ssl/list)
func (s *WebsiteService) POSTSslList(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ssl/list", body)
}

// POSTSslObtain — Apply  ssl (POST /websites/ssl/obtain)
func (s *WebsiteService) POSTSslObtain(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ssl/obtain", body)
}

// POSTSslPush — Push ssl to nodes (POST /websites/ssl/push)
func (s *WebsiteService) POSTSslPush(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ssl/push", body)
}

// POSTSslResolve — Resolve website ssl (POST /websites/ssl/resolve)
func (s *WebsiteService) POSTSslResolve(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ssl/resolve", body)
}

// POSTSslSearch — Page website ssl (POST /websites/ssl/search)
func (s *WebsiteService) POSTSslSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ssl/search", body)
}

// POSTSslUpdate — Update ssl (POST /websites/ssl/update)
func (s *WebsiteService) POSTSslUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ssl/update", body)
}

// POSTSslUpload — Upload ssl (POST /websites/ssl/upload)
func (s *WebsiteService) POSTSslUpload(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ssl/upload", body)
}

// POSTSslUploadFile — Upload SSL file (POST /websites/ssl/upload/file)
func (s *WebsiteService) POSTSslUploadFile(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/ssl/upload/file", body)
}

// GETSslWebsitewebsiteid — Search website ssl by website id (GET /websites/ssl/website/:websiteId)
func (s *WebsiteService) GETSslWebsitewebsiteid(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/websites/ssl/website/:websiteId")
}

// POSTStreamUpdate — Update Stream Config (POST /websites/stream/update)
func (s *WebsiteService) POSTStreamUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/stream/update", body)
}

// POSTUpdate — Update website (POST /websites/update)
func (s *WebsiteService) POSTUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/websites/update", body)
}

// GETLbs — Get website upstreams (GET /websites/{id}/lbs)
func (s *WebsiteService) GETLbs(ctx context.Context, id string) (map[string]any, error) {
	return s.getMap(ctx, fmt.Sprintf("/websites/%s/lbs", id))
}
