// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel

import (
	"context"
)

// AIAccountService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type AIAccountService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *AIAccountService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTAccounts — Create model account (POST /ai/accounts)
func (s *AIAccountService) POSTAccounts(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/accounts", body)
}

// POSTAccountsCounts — Count model accounts by provider (POST /ai/accounts/counts)
func (s *AIAccountService) POSTAccountsCounts(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/accounts/counts", body)
}

// POSTAccountsDelete — Delete model account (POST /ai/accounts/delete)
func (s *AIAccountService) POSTAccountsDelete(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/accounts/delete", body)
}

// POSTAccountsModels — List model account models (POST /ai/accounts/models)
func (s *AIAccountService) POSTAccountsModels(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/accounts/models", body)
}

// POSTAccountsModelsCreate — Create model account model (POST /ai/accounts/models/create)
func (s *AIAccountService) POSTAccountsModelsCreate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/accounts/models/create", body)
}

// POSTAccountsModelsDelete — Delete model account model (POST /ai/accounts/models/delete)
func (s *AIAccountService) POSTAccountsModelsDelete(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/accounts/models/delete", body)
}

// POSTAccountsModelsDiscover — Discover custom provider models (POST /ai/accounts/models/discover)
func (s *AIAccountService) POSTAccountsModelsDiscover(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/accounts/models/discover", body)
}

// POSTAccountsModelsUpdate — Update model account model (POST /ai/accounts/models/update)
func (s *AIAccountService) POSTAccountsModelsUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/accounts/models/update", body)
}

// GETAccountsProviders — Get model account providers (GET /ai/accounts/providers).
// Returns a top-level array of provider DTOs — use GetList or decode into
// a typed []dto.ProviderInfo.
func (s *AIAccountService) GETAccountsProviders(ctx context.Context) ([]any, error) {
	return s.getList(ctx, "/ai/accounts/providers")
}

// POSTAccountsSearch — Page model accounts (POST /ai/accounts/search)
func (s *AIAccountService) POSTAccountsSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/accounts/search", body)
}

// POSTAccountsUpdate — Update model account (POST /ai/accounts/update)
func (s *AIAccountService) POSTAccountsUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/accounts/update", body)
}

// POSTAccountsVerify — Verify model account (POST /ai/accounts/verify)
func (s *AIAccountService) POSTAccountsVerify(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/accounts/verify", body)
}

// AIAgentService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type AIAgentService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *AIAgentService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTAgents — Create Agent (POST /ai/agents)
func (s *AIAgentService) POSTAgents(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents", body)
}

// POSTAgentsAgentBind — Bind Agent role channel (POST /ai/agents/agent/bind)
func (s *AIAgentService) POSTAgentsAgentBind(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/agent/bind", body)
}

// POSTAgentsAgentChannels — Get Agent role channels from config file (POST /ai/agents/agent/channels)
func (s *AIAgentService) POSTAgentsAgentChannels(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/agent/channels", body)
}

// POSTAgentsAgentCreate — Create Agent role (POST /ai/agents/agent/create)
func (s *AIAgentService) POSTAgentsAgentCreate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/agent/create", body)
}

// POSTAgentsAgentDelete — Delete Agent role (POST /ai/agents/agent/delete)
func (s *AIAgentService) POSTAgentsAgentDelete(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/agent/delete", body)
}

// POSTAgentsAgentList — Get configured Agent roles from config file (POST /ai/agents/agent/list)
func (s *AIAgentService) POSTAgentsAgentList(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/agent/list", body)
}

// POSTAgentsAgentMdList — Get Agent role markdown files (POST /ai/agents/agent/md/list)
func (s *AIAgentService) POSTAgentsAgentMdList(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/agent/md/list", body)
}

// POSTAgentsAgentMdUpdate — Update Agent role markdown file (POST /ai/agents/agent/md/update)
func (s *AIAgentService) POSTAgentsAgentMdUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/agent/md/update", body)
}

// POSTAgentsAgentUnbind — Unbind Agent role channel (POST /ai/agents/agent/unbind)
func (s *AIAgentService) POSTAgentsAgentUnbind(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/agent/unbind", body)
}

// POSTAgentsBatchInstall — Batch install Agent (POST /ai/agents/batch/install)
func (s *AIAgentService) POSTAgentsBatchInstall(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/batch/install", body)
}

// POSTAgentsBatchOperate — Batch operate Agent (POST /ai/agents/batch/operate)
func (s *AIAgentService) POSTAgentsBatchOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/batch/operate", body)
}

// POSTAgentsBatchSkillInstall — Batch install Agent Skill (POST /ai/agents/batch/skill/install)
func (s *AIAgentService) POSTAgentsBatchSkillInstall(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/batch/skill/install", body)
}

// POSTAgentsBatchUpgrade — Batch upgrade Agent (POST /ai/agents/batch/upgrade)
func (s *AIAgentService) POSTAgentsBatchUpgrade(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/batch/upgrade", body)
}

// POSTAgentsChannelDelete — Delete Agent channel config (POST /ai/agents/channel/delete)
func (s *AIAgentService) POSTAgentsChannelDelete(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/channel/delete", body)
}

// POSTAgentsChannelDingtalkGet — Get Agent DingTalk channel config (POST /ai/agents/channel/dingtalk/get)
func (s *AIAgentService) POSTAgentsChannelDingtalkGet(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/channel/dingtalk/get", body)
}

// POSTAgentsChannelDingtalkUpdate — Update Agent DingTalk channel config (POST /ai/agents/channel/dingtalk/update)
func (s *AIAgentService) POSTAgentsChannelDingtalkUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/channel/dingtalk/update", body)
}

// POSTAgentsChannelDiscordGet — Get Agent Discord channel config (POST /ai/agents/channel/discord/get)
func (s *AIAgentService) POSTAgentsChannelDiscordGet(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/channel/discord/get", body)
}

// POSTAgentsChannelDiscordUpdate — Update Agent Discord channel config (POST /ai/agents/channel/discord/update)
func (s *AIAgentService) POSTAgentsChannelDiscordUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/channel/discord/update", body)
}

// POSTAgentsChannelFeishuGet — Get Agent Feishu channel config (POST /ai/agents/channel/feishu/get)
func (s *AIAgentService) POSTAgentsChannelFeishuGet(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/channel/feishu/get", body)
}

// POSTAgentsChannelFeishuUpdate — Update Agent Feishu channel config (POST /ai/agents/channel/feishu/update)
func (s *AIAgentService) POSTAgentsChannelFeishuUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/channel/feishu/update", body)
}

// POSTAgentsChannelPairingApprove — Approve Agent channel pairing code (POST /ai/agents/channel/pairing/approve)
func (s *AIAgentService) POSTAgentsChannelPairingApprove(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/channel/pairing/approve", body)
}

// POSTAgentsChannelQqbotGet — Get Agent QQ Bot channel config (POST /ai/agents/channel/qqbot/get)
func (s *AIAgentService) POSTAgentsChannelQqbotGet(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/channel/qqbot/get", body)
}

// POSTAgentsChannelQqbotUpdate — Update Agent QQ Bot channel config (POST /ai/agents/channel/qqbot/update)
func (s *AIAgentService) POSTAgentsChannelQqbotUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/channel/qqbot/update", body)
}

// POSTAgentsChannelTelegramGet — Get Agent Telegram channel config (POST /ai/agents/channel/telegram/get)
func (s *AIAgentService) POSTAgentsChannelTelegramGet(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/channel/telegram/get", body)
}

// POSTAgentsChannelTelegramUpdate — Update Agent Telegram channel config (POST /ai/agents/channel/telegram/update)
func (s *AIAgentService) POSTAgentsChannelTelegramUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/channel/telegram/update", body)
}

// POSTAgentsChannelWecomGet — Get Agent QQ Bot channel config (POST /ai/agents/channel/wecom/get)
func (s *AIAgentService) POSTAgentsChannelWecomGet(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/channel/wecom/get", body)
}

// POSTAgentsChannelWecomUpdate — Update Agent WeCom channel config (POST /ai/agents/channel/wecom/update)
func (s *AIAgentService) POSTAgentsChannelWecomUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/channel/wecom/update", body)
}

// POSTAgentsChannelWeixinGet — Get Agent Weixin channel config (POST /ai/agents/channel/weixin/get)
func (s *AIAgentService) POSTAgentsChannelWeixinGet(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/channel/weixin/get", body)
}

// POSTAgentsChannelWeixinLogin — Login Agent Weixin channel (POST /ai/agents/channel/weixin/login)
func (s *AIAgentService) POSTAgentsChannelWeixinLogin(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/channel/weixin/login", body)
}

// POSTAgentsConfigfileGet — Get Agent config file (POST /ai/agents/config-file/get)
func (s *AIAgentService) POSTAgentsConfigfileGet(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/config-file/get", body)
}

// POSTAgentsConfigfileUpdate — Update Agent config file (POST /ai/agents/config-file/update)
func (s *AIAgentService) POSTAgentsConfigfileUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/config-file/update", body)
}

// POSTAgentsDelete — Delete Agent (POST /ai/agents/delete)
func (s *AIAgentService) POSTAgentsDelete(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/delete", body)
}

// POSTAgentsDeleteCheck — Delete check Agent (POST /ai/agents/delete/check)
func (s *AIAgentService) POSTAgentsDeleteCheck(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/delete/check", body)
}

// POSTAgentsHermesChatSessions — Get Hermes chat sessions (POST /ai/agents/hermes/chat/sessions)
func (s *AIAgentService) POSTAgentsHermesChatSessions(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/hermes/chat/sessions", body)
}

// POSTAgentsHermesChatSessionsDelete — Delete Hermes chat session (POST /ai/agents/hermes/chat/sessions/delete)
func (s *AIAgentService) POSTAgentsHermesChatSessionsDelete(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/hermes/chat/sessions/delete", body)
}

// POSTAgentsHermesChatSessionsRename — Rename Hermes chat session (POST /ai/agents/hermes/chat/sessions/rename)
func (s *AIAgentService) POSTAgentsHermesChatSessionsRename(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/hermes/chat/sessions/rename", body)
}

// POSTAgentsModelGet — Get Agent model config (POST /ai/agents/model/get)
func (s *AIAgentService) POSTAgentsModelGet(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/model/get", body)
}

// POSTAgentsModelUpdate — Update Agent model config (POST /ai/agents/model/update)
func (s *AIAgentService) POSTAgentsModelUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/model/update", body)
}

// POSTAgentsOtherGet — Get Agent Other config (POST /ai/agents/other/get)
func (s *AIAgentService) POSTAgentsOtherGet(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/other/get", body)
}

// POSTAgentsOtherUpdate — Update Agent Other config (POST /ai/agents/other/update)
func (s *AIAgentService) POSTAgentsOtherUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/other/update", body)
}

// POSTAgentsOverview — Get Agent overview (POST /ai/agents/overview)
func (s *AIAgentService) POSTAgentsOverview(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/overview", body)
}

// POSTAgentsPluginCheck — Check Agent plugin installation status (POST /ai/agents/plugin/check)
func (s *AIAgentService) POSTAgentsPluginCheck(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/plugin/check", body)
}

// POSTAgentsPluginInstall — Install Agent plugin (POST /ai/agents/plugin/install)
func (s *AIAgentService) POSTAgentsPluginInstall(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/plugin/install", body)
}

// POSTAgentsPluginUninstall — Uninstall Agent plugin (POST /ai/agents/plugin/uninstall)
func (s *AIAgentService) POSTAgentsPluginUninstall(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/plugin/uninstall", body)
}

// POSTAgentsPluginUpgrade — Upgrade Agent plugin (POST /ai/agents/plugin/upgrade)
func (s *AIAgentService) POSTAgentsPluginUpgrade(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/plugin/upgrade", body)
}

// POSTAgentsPluginsInstall — Install an OpenClaw marketplace plugin (POST /ai/agents/plugins/install)
func (s *AIAgentService) POSTAgentsPluginsInstall(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/plugins/install", body)
}

// POSTAgentsPluginsList — List OpenClaw plugins (POST /ai/agents/plugins/list)
func (s *AIAgentService) POSTAgentsPluginsList(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/plugins/list", body)
}

// POSTAgentsPluginsOperate — Operate an OpenClaw plugin (POST /ai/agents/plugins/operate)
func (s *AIAgentService) POSTAgentsPluginsOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/plugins/operate", body)
}

// POSTAgentsPluginsSearch — Search OpenClaw plugins (POST /ai/agents/plugins/search)
func (s *AIAgentService) POSTAgentsPluginsSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/plugins/search", body)
}

// POSTAgentsRemark — Update Agent remark (POST /ai/agents/remark)
func (s *AIAgentService) POSTAgentsRemark(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/remark", body)
}

// POSTAgentsSearch — Page Agents (POST /ai/agents/search)
func (s *AIAgentService) POSTAgentsSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/search", body)
}

// POSTAgentsSecurityGet — Get Agent Security config (POST /ai/agents/security/get)
func (s *AIAgentService) POSTAgentsSecurityGet(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/security/get", body)
}

// POSTAgentsSecurityUpdate — Update Agent Security config (POST /ai/agents/security/update)
func (s *AIAgentService) POSTAgentsSecurityUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/security/update", body)
}

// POSTAgentsSkillsInstall — Install Agent skill (POST /ai/agents/skills/install)
func (s *AIAgentService) POSTAgentsSkillsInstall(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/skills/install", body)
}

// POSTAgentsSkillsList — List Agent skills (POST /ai/agents/skills/list)
func (s *AIAgentService) POSTAgentsSkillsList(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/skills/list", body)
}

// POSTAgentsSkillsSearch — Search Agent skills (POST /ai/agents/skills/search)
func (s *AIAgentService) POSTAgentsSkillsSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/skills/search", body)
}

// POSTAgentsSkillsUninstall — Uninstall Agent skill (POST /ai/agents/skills/uninstall)
func (s *AIAgentService) POSTAgentsSkillsUninstall(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/skills/uninstall", body)
}

// POSTAgentsSkillsUpdate — Update Agent skill status (POST /ai/agents/skills/update)
func (s *AIAgentService) POSTAgentsSkillsUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/skills/update", body)
}

// POSTAgentsTokenReset — Reset Agent token (POST /ai/agents/token/reset)
func (s *AIAgentService) POSTAgentsTokenReset(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/token/reset", body)
}

// POSTAgentsWebsiteBind — Bind Agent website (POST /ai/agents/website/bind)
func (s *AIAgentService) POSTAgentsWebsiteBind(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/website/bind", body)
}

// POSTAgentsWebsiteUnbind — Unbind Agent website (POST /ai/agents/website/unbind)
func (s *AIAgentService) POSTAgentsWebsiteUnbind(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/agents/website/unbind", body)
}

// AIDomainService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type AIDomainService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *AIDomainService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTDomainBind — Bind domain (POST /ai/domain/bind)
func (s *AIDomainService) POSTDomainBind(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/domain/bind", body)
}

// POSTDomainGet — Get bind domain (POST /ai/domain/get)
func (s *AIDomainService) POSTDomainGet(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/domain/get", body)
}

// POSTDomainUpdate — Update bind domain (POST /ai/domain/update)
func (s *AIDomainService) POSTDomainUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/domain/update", body)
}

// AIGpuService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type AIGpuService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *AIGpuService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// GETGpuLoad — Load gpu / xpu info (GET /ai/gpu/load)
func (s *AIGpuService) GETGpuLoad(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/ai/gpu/load")
}

// GETGpuOptions — Get CPU options (GET /ai/gpu/options)
func (s *AIGpuService) GETGpuOptions(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/ai/gpu/options")
}

// POSTGpuSearch — Load monitor data (POST /ai/gpu/search)
func (s *AIGpuService) POSTGpuSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/gpu/search", body)
}

// AIMcpService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type AIMcpService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *AIMcpService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTMcpDomainBind — Bind Domain for mcp server (POST /ai/mcp/domain/bind)
func (s *AIMcpService) POSTMcpDomainBind(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/mcp/domain/bind", body)
}

// GETMcpDomainGet — Get bin Domain for mcp server (GET /ai/mcp/domain/get)
func (s *AIMcpService) GETMcpDomainGet(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/ai/mcp/domain/get")
}

// POSTMcpDomainUpdate — Update bind Domain for mcp server (POST /ai/mcp/domain/update)
func (s *AIMcpService) POSTMcpDomainUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/mcp/domain/update", body)
}

// POSTMcpSearch — List mcp servers (POST /ai/mcp/search)
func (s *AIMcpService) POSTMcpSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/mcp/search", body)
}

// POSTMcpServer — Create mcp server (POST /ai/mcp/server)
func (s *AIMcpService) POSTMcpServer(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/mcp/server", body)
}

// POSTMcpServerConnectionTest — Test mcp server connection (POST /ai/mcp/server/connection/test)
func (s *AIMcpService) POSTMcpServerConnectionTest(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/mcp/server/connection/test", body)
}

// POSTMcpServerDel — Delete mcp server (POST /ai/mcp/server/del)
func (s *AIMcpService) POSTMcpServerDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/mcp/server/del", body)
}

// POSTMcpServerDetail — Load mcp server detail (POST /ai/mcp/server/detail)
func (s *AIMcpService) POSTMcpServerDetail(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/mcp/server/detail", body)
}

// POSTMcpServerOp — Operate mcp server (POST /ai/mcp/server/op)
func (s *AIMcpService) POSTMcpServerOp(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/mcp/server/op", body)
}

// POSTMcpServerStatusSync — Sync mcp server status (POST /ai/mcp/server/status/sync)
func (s *AIMcpService) POSTMcpServerStatusSync(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/mcp/server/status/sync", body)
}

// POSTMcpServerUpdate — Update mcp server (POST /ai/mcp/server/update)
func (s *AIMcpService) POSTMcpServerUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/mcp/server/update", body)
}

// AIOllamaService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type AIOllamaService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *AIOllamaService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTOllamaClose — Close Ollama model conn (POST /ai/ollama/close)
func (s *AIOllamaService) POSTOllamaClose(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/ollama/close", body)
}

// POSTOllamaModel — Create Ollama model (POST /ai/ollama/model)
func (s *AIOllamaService) POSTOllamaModel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/ollama/model", body)
}

// POSTOllamaModelDel — Delete Ollama model (POST /ai/ollama/model/del)
func (s *AIOllamaService) POSTOllamaModelDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/ollama/model/del", body)
}

// POSTOllamaModelLoad — Page Ollama models (POST /ai/ollama/model/load)
func (s *AIOllamaService) POSTOllamaModelLoad(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/ollama/model/load", body)
}

// POSTOllamaModelRecreate — Rereate Ollama model (POST /ai/ollama/model/recreate)
func (s *AIOllamaService) POSTOllamaModelRecreate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/ollama/model/recreate", body)
}

// POSTOllamaModelSearch — Page Ollama models (POST /ai/ollama/model/search)
func (s *AIOllamaService) POSTOllamaModelSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/ollama/model/search", body)
}

// POSTOllamaModelSync — Sync Ollama model list (POST /ai/ollama/model/sync)
func (s *AIOllamaService) POSTOllamaModelSync(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/ollama/model/sync", body)
}

// AITensorService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type AITensorService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *AITensorService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTTensorrtCreate — Create TensorRT LLM (POST /ai/tensorrt/create)
func (s *AITensorService) POSTTensorrtCreate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/tensorrt/create", body)
}

// POSTTensorrtDelete — Delete TensorRT LLM (POST /ai/tensorrt/delete)
func (s *AITensorService) POSTTensorrtDelete(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/tensorrt/delete", body)
}

// POSTTensorrtOperate — Operate TensorRT LLM (POST /ai/tensorrt/operate)
func (s *AITensorService) POSTTensorrtOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/tensorrt/operate", body)
}

// POSTTensorrtSearch — Page TensorRT LLMs (POST /ai/tensorrt/search)
func (s *AITensorService) POSTTensorrtSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/tensorrt/search", body)
}

// POSTTensorrtUpdate — Update TensorRT LLM (POST /ai/tensorrt/update)
func (s *AITensorService) POSTTensorrtUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/ai/tensorrt/update", body)
}
