// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel

import (
	"context"
)

// HealthService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type HealthService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *HealthService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// GETCheck — Check health (GET /health/check)
func (s *HealthService) GETCheck(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/health/check")
}

// OpenRestyService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type OpenRestyService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *OpenRestyService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// GETOpenresty — Load OpenResty conf (GET /openresty)
func (s *OpenRestyService) GETOpenresty(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/openresty")
}

// POSTBuild — Build OpenResty (POST /openresty/build)
func (s *OpenRestyService) POSTBuild(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/openresty/build", body)
}

// POSTFile — Update OpenResty conf by upload file (POST /openresty/file)
func (s *OpenRestyService) POSTFile(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/openresty/file", body)
}

// GETHttps — Get default HTTPs status (GET /openresty/https)
func (s *OpenRestyService) GETHttps(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/openresty/https")
}

// POSTHttps — Operate default HTTPs (POST /openresty/https)
func (s *OpenRestyService) POSTHttps(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/openresty/https", body)
}

// GETModules — Get OpenResty modules (GET /openresty/modules)
func (s *OpenRestyService) GETModules(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/openresty/modules")
}

// POSTModulesUpdate — Update OpenResty module (POST /openresty/modules/update)
func (s *OpenRestyService) POSTModulesUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/openresty/modules/update", body)
}

// POSTScope — Load partial OpenResty conf (POST /openresty/scope)
func (s *OpenRestyService) POSTScope(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/openresty/scope", body)
}

// GETStatus — Load OpenResty status info (GET /openresty/status)
func (s *OpenRestyService) GETStatus(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/openresty/status")
}

// POSTUpdate — Update OpenResty conf (POST /openresty/update)
func (s *OpenRestyService) POSTUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/openresty/update", body)
}

// POSTRuntimes — Create runtime (POST /runtimes)
func (s *RuntimeService) POSTRuntimes(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes", body)
}

// GETid — Get runtime (GET /runtimes/:id)
func (s *RuntimeService) GETid(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/runtimes/:id")
}

// POSTDel — Delete runtime (POST /runtimes/del)
func (s *RuntimeService) POSTDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/del", body)
}

// GETInstalledDeleteCheckid — Delete runtime (GET /runtimes/installed/delete/check/:id)
func (s *RuntimeService) GETInstalledDeleteCheckid(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/runtimes/installed/delete/check/:id")
}

// POSTNodeModules — Get Node modules (POST /runtimes/node/modules)
func (s *RuntimeService) POSTNodeModules(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/node/modules", body)
}

// POSTNodeModulesOperate — Operate Node modules (POST /runtimes/node/modules/operate)
func (s *RuntimeService) POSTNodeModulesOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/node/modules/operate", body)
}

// POSTNodePackage — Get Node package scripts (POST /runtimes/node/package)
func (s *RuntimeService) POSTNodePackage(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/node/package", body)
}

// POSTOperate — Operate runtime (POST /runtimes/operate)
func (s *RuntimeService) POSTOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/operate", body)
}

// GETPhpidExtensions — Get php runtime extension (GET /runtimes/php/:id/extensions)
func (s *RuntimeService) GETPhpidExtensions(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/runtimes/php/:id/extensions")
}

// POSTPhpConfig — Update runtime php conf (POST /runtimes/php/config)
func (s *RuntimeService) POSTPhpConfig(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/php/config", body)
}

// GETPhpConfigid — Load php runtime conf (GET /runtimes/php/config/:id)
func (s *RuntimeService) GETPhpConfigid(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/runtimes/php/config/:id")
}

// GETPhpContainerid — Get PHP container config (GET /runtimes/php/container/:id)
func (s *RuntimeService) GETPhpContainerid(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/runtimes/php/container/:id")
}

// POSTPhpContainerUpdate — Update PHP container config (POST /runtimes/php/container/update)
func (s *RuntimeService) POSTPhpContainerUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/php/container/update", body)
}

// POSTPhpExtensions — Create Extensions (POST /runtimes/php/extensions)
func (s *RuntimeService) POSTPhpExtensions(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/php/extensions", body)
}

// POSTPhpExtensionsDel — Delete Extensions (POST /runtimes/php/extensions/del)
func (s *RuntimeService) POSTPhpExtensionsDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/php/extensions/del", body)
}

// POSTPhpExtensionsInstall — Install php extension (POST /runtimes/php/extensions/install)
func (s *RuntimeService) POSTPhpExtensionsInstall(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/php/extensions/install", body)
}

// POSTPhpExtensionsSearch — Page Extensions (POST /runtimes/php/extensions/search)
func (s *RuntimeService) POSTPhpExtensionsSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/php/extensions/search", body)
}

// POSTPhpExtensionsUninstall — UnInstall php extension (POST /runtimes/php/extensions/uninstall)
func (s *RuntimeService) POSTPhpExtensionsUninstall(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/php/extensions/uninstall", body)
}

// POSTPhpExtensionsUpdate — Update Extensions (POST /runtimes/php/extensions/update)
func (s *RuntimeService) POSTPhpExtensionsUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/php/extensions/update", body)
}

// POSTPhpFile — Get php conf file (POST /runtimes/php/file)
func (s *RuntimeService) POSTPhpFile(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/php/file", body)
}

// POSTPhpFpmConfig — Update fpm config (POST /runtimes/php/fpm/config)
func (s *RuntimeService) POSTPhpFpmConfig(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/php/fpm/config", body)
}

// GETPhpFpmConfigid — Get fpm config (GET /runtimes/php/fpm/config/:id)
func (s *RuntimeService) GETPhpFpmConfigid(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/runtimes/php/fpm/config/:id")
}

// GETPhpFpmStatusid — Get PHP runtime status (GET /runtimes/php/fpm/status/:id)
func (s *RuntimeService) GETPhpFpmStatusid(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/runtimes/php/fpm/status/:id")
}

// POSTPhpUpdate — Update php conf file (POST /runtimes/php/update)
func (s *RuntimeService) POSTPhpUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/php/update", body)
}

// POSTRemark — Update runtime remark (POST /runtimes/remark)
func (s *RuntimeService) POSTRemark(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/remark", body)
}

// POSTSearch — List runtimes (POST /runtimes/search)
func (s *RuntimeService) POSTSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/search", body)
}

// POSTSupervisorProcess — Operate supervisor process (POST /runtimes/supervisor/process)
func (s *RuntimeService) POSTSupervisorProcess(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/supervisor/process", body)
}

// GETSupervisorProcessid — Get supervisor process (GET /runtimes/supervisor/process/:id)
func (s *RuntimeService) GETSupervisorProcessid(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/runtimes/supervisor/process/:id")
}

// POSTSupervisorProcessFile — Operate supervisor process file (POST /runtimes/supervisor/process/file)
func (s *RuntimeService) POSTSupervisorProcessFile(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/supervisor/process/file", body)
}

// POSTSync — Sync runtime status (POST /runtimes/sync)
func (s *RuntimeService) POSTSync(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/sync", body)
}

// POSTUpdate — Update runtime (POST /runtimes/update)
func (s *RuntimeService) POSTUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/runtimes/update", body)
}
