// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel

import (
	"context"
	"fmt"
)

// HostDiskService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type HostDiskService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *HostDiskService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// GETDisks — Get complete disk information (GET /hosts/disks)
func (s *HostDiskService) GETDisks(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/hosts/disks")
}

// POSTDisksMount — Mount disk (POST /hosts/disks/mount)
func (s *HostDiskService) POSTDisksMount(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/disks/mount", body)
}

// POSTDisksPartition — Partition disk (POST /hosts/disks/partition)
func (s *HostDiskService) POSTDisksPartition(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/disks/partition", body)
}

// POSTDisksUnmount — Unmount disk (POST /hosts/disks/unmount)
func (s *HostDiskService) POSTDisksUnmount(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/disks/unmount", body)
}

// HostFirewallService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type HostFirewallService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *HostFirewallService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTFirewallBase — Load firewall base info (POST /hosts/firewall/base)
func (s *HostFirewallService) POSTFirewallBase(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/firewall/base", body)
}

// POSTFirewallBatch — Batch operate rule (POST /hosts/firewall/batch)
func (s *HostFirewallService) POSTFirewallBatch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/firewall/batch", body)
}

// POSTFirewallFilterChainStatus — load chain status with name (POST /hosts/firewall/filter/chain/status)
func (s *HostFirewallService) POSTFirewallFilterChainStatus(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/firewall/filter/chain/status", body)
}

// POSTFirewallFilterOperate — Apply/Unload/Init iptables filter (POST /hosts/firewall/filter/operate)
func (s *HostFirewallService) POSTFirewallFilterOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/firewall/filter/operate", body)
}

// POSTFirewallFilterRuleBatch — Batch operate iptables filter rules (POST /hosts/firewall/filter/rule/batch)
func (s *HostFirewallService) POSTFirewallFilterRuleBatch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/firewall/filter/rule/batch", body)
}

// POSTFirewallFilterRuleOperate — Operate iptables filter rule (POST /hosts/firewall/filter/rule/operate)
func (s *HostFirewallService) POSTFirewallFilterRuleOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/firewall/filter/rule/operate", body)
}

// POSTFirewallFilterRuleSearch — search iptables filter rules (POST /hosts/firewall/filter/rule/search)
func (s *HostFirewallService) POSTFirewallFilterRuleSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/firewall/filter/rule/search", body)
}

// POSTFirewallForward — Operate forward rule (POST /hosts/firewall/forward)
func (s *HostFirewallService) POSTFirewallForward(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/firewall/forward", body)
}

// POSTFirewallIp — Operate Ip rule (POST /hosts/firewall/ip)
func (s *HostFirewallService) POSTFirewallIp(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/firewall/ip", body)
}

// POSTFirewallOperate — Operate firewall (POST /hosts/firewall/operate)
func (s *HostFirewallService) POSTFirewallOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/firewall/operate", body)
}

// POSTFirewallPort — Create group (POST /hosts/firewall/port)
func (s *HostFirewallService) POSTFirewallPort(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/firewall/port", body)
}

// POSTFirewallSearch — Page firewall rules (POST /hosts/firewall/search)
func (s *HostFirewallService) POSTFirewallSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/firewall/search", body)
}

// POSTFirewallUpdateAddr — Update Ip rule (POST /hosts/firewall/update/addr)
func (s *HostFirewallService) POSTFirewallUpdateAddr(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/firewall/update/addr", body)
}

// POSTFirewallUpdateDescription — Update rule description (POST /hosts/firewall/update/description)
func (s *HostFirewallService) POSTFirewallUpdateDescription(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/firewall/update/description", body)
}

// POSTFirewallUpdatePort — Update port rule (POST /hosts/firewall/update/port)
func (s *HostFirewallService) POSTFirewallUpdatePort(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/firewall/update/port", body)
}

// HostMonitorService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type HostMonitorService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *HostMonitorService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTMonitorClean — Clean monitor data (POST /hosts/monitor/clean)
func (s *HostMonitorService) POSTMonitorClean(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/monitor/clean", body)
}

// GETMonitorIooptions — Get IO options (GET /hosts/monitor/iooptions)
func (s *HostMonitorService) GETMonitorIooptions(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/hosts/monitor/iooptions")
}

// GETMonitorNetoptions — Get network options (GET /hosts/monitor/netoptions)
func (s *HostMonitorService) GETMonitorNetoptions(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/hosts/monitor/netoptions")
}

// POSTMonitorSearch — Load monitor data (POST /hosts/monitor/search)
func (s *HostMonitorService) POSTMonitorSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/monitor/search", body)
}

// GETMonitorSetting — Load monitor setting (GET /hosts/monitor/setting)
func (s *HostMonitorService) GETMonitorSetting(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/hosts/monitor/setting")
}

// POSTMonitorSettingUpdate — Update monitor setting (POST /hosts/monitor/setting/update)
func (s *HostMonitorService) POSTMonitorSettingUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/monitor/setting/update", body)
}

// HostOtherService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type HostOtherService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *HostOtherService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTHosts — Create host (POST /hosts)
func (s *HostOtherService) POSTHosts(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts", body)
}

// GETComponents — Check if a system component exists (GET /hosts/components/{name})
func (s *HostOtherService) GETComponents(ctx context.Context, name string) (map[string]any, error) {
	return s.getMap(ctx, fmt.Sprintf("/hosts/components/%s", name))
}

// POSTDel — Delete host (POST /hosts/del)
func (s *HostOtherService) POSTDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/del", body)
}

// POSTInfo — Get host by ID (POST /hosts/info)
func (s *HostOtherService) POSTInfo(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/info", body)
}

// POSTSearch — Search host (POST /hosts/search)
func (s *HostOtherService) POSTSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/search", body)
}

// GETTerminalContainer — Ws container terminal (GET /hosts/terminal/container)
func (s *HostOtherService) GETTerminalContainer(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/hosts/terminal/container")
}

// GETTerminalLocal — Ws local terminal (GET /hosts/terminal/local)
func (s *HostOtherService) GETTerminalLocal(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/hosts/terminal/local")
}

// GETTerminalSsh — Ws host SSH (GET /hosts/terminal/ssh)
func (s *HostOtherService) GETTerminalSsh(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/hosts/terminal/ssh")
}

// POSTTestByid — Test by ID (POST /hosts/test/byid)
func (s *HostOtherService) POSTTestByid(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/test/byid", body)
}

// POSTTestByinfo — Test by info (POST /hosts/test/byinfo)
func (s *HostOtherService) POSTTestByinfo(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/test/byinfo", body)
}

// POSTTree — Host tree (POST /hosts/tree)
func (s *HostOtherService) POSTTree(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/tree", body)
}

// POSTUpdate — Update host (POST /hosts/update)
func (s *HostOtherService) POSTUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/update", body)
}

// POSTUpdateGroup — Update host group (POST /hosts/update/group)
func (s *HostOtherService) POSTUpdateGroup(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/update/group", body)
}

// HostRuntimeService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type HostRuntimeService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *HostRuntimeService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// GETDiagnosticsGoroutines — Load grouped goroutine snapshot (GET /hosts/diagnostics/goroutines)
func (s *HostRuntimeService) GETDiagnosticsGoroutines(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/hosts/diagnostics/goroutines")
}

// POSTDiagnosticsProfiles — Capture runtime profile (POST /hosts/diagnostics/profiles)
func (s *HostRuntimeService) POSTDiagnosticsProfiles(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/diagnostics/profiles", body)
}

// GETDiagnosticsSummary — Load runtime diagnostics summary (GET /hosts/diagnostics/summary)
func (s *HostRuntimeService) GETDiagnosticsSummary(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/hosts/diagnostics/summary")
}

// HostSshService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type HostSshService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *HostSshService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTSshCert — Generate host SSH secret (POST /hosts/ssh/cert)
func (s *HostSshService) POSTSshCert(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/ssh/cert", body)
}

// POSTSshCertDelete — Delete host SSH secret (POST /hosts/ssh/cert/delete)
func (s *HostSshService) POSTSshCertDelete(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/ssh/cert/delete", body)
}

// POSTSshCertSearch — Load host SSH secret (POST /hosts/ssh/cert/search)
func (s *HostSshService) POSTSshCertSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/ssh/cert/search", body)
}

// POSTSshCertSync — Sycn host SSH secret (POST /hosts/ssh/cert/sync)
func (s *HostSshService) POSTSshCertSync(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/ssh/cert/sync", body)
}

// POSTSshCertUpdate — Update host SSH secret (POST /hosts/ssh/cert/update)
func (s *HostSshService) POSTSshCertUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/ssh/cert/update", body)
}

// POSTSshFile — Load host SSH conf (POST /hosts/ssh/file)
func (s *HostSshService) POSTSshFile(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/ssh/file", body)
}

// POSTSshFileUpdate — Update host SSH setting by file (POST /hosts/ssh/file/update)
func (s *HostSshService) POSTSshFileUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/ssh/file/update", body)
}

// POSTSshLog — Load host SSH logs (POST /hosts/ssh/log)
func (s *HostSshService) POSTSshLog(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/ssh/log", body)
}

// POSTSshLogClean — Clean host SSH logs (POST /hosts/ssh/log/clean)
func (s *HostSshService) POSTSshLogClean(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/ssh/log/clean", body)
}

// POSTSshLogExport — Export host SSH logs (POST /hosts/ssh/log/export)
func (s *HostSshService) POSTSshLogExport(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/ssh/log/export", body)
}

// POSTSshOperate — Operate SSH (POST /hosts/ssh/operate)
func (s *HostSshService) POSTSshOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/ssh/operate", body)
}

// POSTSshSearch — Load host SSH setting info (POST /hosts/ssh/search)
func (s *HostSshService) POSTSshSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/ssh/search", body)
}

// POSTSshUpdate — Update host SSH setting (POST /hosts/ssh/update)
func (s *HostSshService) POSTSshUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/ssh/update", body)
}

// HostToolService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type HostToolService struct{ ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *HostToolService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTToolConfigGet — Get tool config (POST /hosts/tool/config/get)
func (s *HostToolService) POSTToolConfigGet(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/tool/config/get", body)
}

// POSTToolConfigSet — Update tool config (POST /hosts/tool/config/set)
func (s *HostToolService) POSTToolConfigSet(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/tool/config/set", body)
}

// POSTToolInit — Create Host tool Config (POST /hosts/tool/init)
func (s *HostToolService) POSTToolInit(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/tool/init", body)
}

// POSTToolOperate — Operate tool (POST /hosts/tool/operate)
func (s *HostToolService) POSTToolOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/tool/operate", body)
}

// POSTToolStatus — Get tool status (POST /hosts/tool/status)
func (s *HostToolService) POSTToolStatus(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/tool/status", body)
}

// GETToolSupervisorProcess — Get Supervisor process config (GET /hosts/tool/supervisor/process)
func (s *HostToolService) GETToolSupervisorProcess(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/hosts/tool/supervisor/process")
}

// POSTToolSupervisorProcess — Create Supervisor process (POST /hosts/tool/supervisor/process)
func (s *HostToolService) POSTToolSupervisorProcess(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/tool/supervisor/process", body)
}

// POSTToolSupervisorProcessFile — Operate Supervisor process config file (POST /hosts/tool/supervisor/process/file)
func (s *HostToolService) POSTToolSupervisorProcessFile(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/tool/supervisor/process/file", body)
}

// POSTToolSupervisorProcessFileGet — Get Supervisor process config file (POST /hosts/tool/supervisor/process/file/get)
func (s *HostToolService) POSTToolSupervisorProcessFileGet(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/hosts/tool/supervisor/process/file/get", body)
}
