// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel
import (
	"context"
)

// GETBasedir — Load local backup dir (GET /settings/basedir)
func (s *SettingsService) GETBasedir(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/settings/basedir")
}

// POSTDescriptionSave — Save common description (POST /settings/description/save)
func (s *SettingsService) POSTDescriptionSave(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/description/save", body)
}

// POSTFilehistorySearch — Load file history setting info (POST /settings/file-history/search)
func (s *SettingsService) POSTFilehistorySearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/file-history/search", body)
}

// POSTFilehistoryUpdate — Update file history setting (POST /settings/file-history/update)
func (s *SettingsService) POSTFilehistoryUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/file-history/update", body)
}

// POSTFilesAiSearch — Get file manage AI setting info (POST /settings/files/ai/search)
func (s *SettingsService) POSTFilesAiSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/files/ai/search", body)
}

// POSTFilesAiUpdate — Update file manage AI setting (POST /settings/files/ai/update)
func (s *SettingsService) POSTFilesAiUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/files/ai/update", body)
}

// POSTSearch — Load system setting info (POST /settings/search)
func (s *SettingsService) POSTSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/search", body)
}

// GETSearchAvailable — Load system available status (GET /settings/search/available)
func (s *SettingsService) GETSearchAvailable(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/settings/search/available")
}

// POSTSnapshot — Create system snapshot (POST /settings/snapshot)
func (s *SettingsService) POSTSnapshot(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/snapshot", body)
}

// POSTSnapshotDel — Delete system backup (POST /settings/snapshot/del)
func (s *SettingsService) POSTSnapshotDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/snapshot/del", body)
}

// POSTSnapshotDescriptionUpdate — Update snapshot description (POST /settings/snapshot/description/update)
func (s *SettingsService) POSTSnapshotDescriptionUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/snapshot/description/update", body)
}

// POSTSnapshotImport — Import system snapshot (POST /settings/snapshot/import)
func (s *SettingsService) POSTSnapshotImport(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/snapshot/import", body)
}

// GETSnapshotLoad — Load system snapshot data (GET /settings/snapshot/load)
func (s *SettingsService) GETSnapshotLoad(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/settings/snapshot/load")
}

// POSTSnapshotRecover — Recover system backup (POST /settings/snapshot/recover)
func (s *SettingsService) POSTSnapshotRecover(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/snapshot/recover", body)
}

// POSTSnapshotRecreate — Recreate system snapshot (POST /settings/snapshot/recreate)
func (s *SettingsService) POSTSnapshotRecreate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/snapshot/recreate", body)
}

// POSTSnapshotRollback — Rollback system backup (POST /settings/snapshot/rollback)
func (s *SettingsService) POSTSnapshotRollback(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/snapshot/rollback", body)
}

// POSTSnapshotSearch — Page system snapshot (POST /settings/snapshot/search)
func (s *SettingsService) POSTSnapshotSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/snapshot/search", body)
}

// POSTSsh — Save local conn info (POST /settings/ssh)
func (s *SettingsService) POSTSsh(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/ssh", body)
}

// POSTSshCheck — Check local conn (POST /settings/ssh/check)
func (s *SettingsService) POSTSshCheck(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/ssh/check", body)
}

// POSTSshCheckInfo — Check local conn info (POST /settings/ssh/check/info)
func (s *SettingsService) POSTSshCheckInfo(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/ssh/check/info", body)
}

// GETSshConn — Load local conn (GET /settings/ssh/conn)
func (s *SettingsService) GETSshConn(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/settings/ssh/conn")
}

// POSTSshDefault — Update local is conn (POST /settings/ssh/default)
func (s *SettingsService) POSTSshDefault(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/ssh/default", body)
}

// POSTTerminalAiSearch — Get terminal AI setting info (POST /settings/terminal/ai/search)
func (s *SettingsService) POSTTerminalAiSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/terminal/ai/search", body)
}

// POSTTerminalAiUpdate — Update terminal AI setting (POST /settings/terminal/ai/update)
func (s *SettingsService) POSTTerminalAiUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/terminal/ai/update", body)
}

// POSTUpdate — Update system setting (POST /settings/update)
func (s *SettingsService) POSTUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/settings/update", body)
}

// GETWebsiteDir — Load website dir (GET /settings/website/dir)
func (s *SettingsService) GETWebsiteDir(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/settings/website/dir")
}

