// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel
import (
	"context"
)

// POSTGroups — Create group (POST /groups)
func (s *GroupsService) POSTGroups(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/groups", body)
}

// POSTDel — Delete group (POST /groups/del)
func (s *GroupsService) POSTDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/groups/del", body)
}

// POSTSearch — List groups (POST /groups/search)
func (s *GroupsService) POSTSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/groups/search", body)
}

// POSTUpdate — Update group (POST /groups/update)
func (s *GroupsService) POSTUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/groups/update", body)
}

