// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel
import (
	"context"
)

// POSTCronjobs — Create cronjob (POST /cronjobs)
func (s *CronjobService) POSTCronjobs(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/cronjobs", body)
}

// POSTDel — Delete cronjob (POST /cronjobs/del)
func (s *CronjobService) POSTDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/cronjobs/del", body)
}

// POSTExport — Export cronjob list (POST /cronjobs/export)
func (s *CronjobService) POSTExport(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/cronjobs/export", body)
}

// POSTGroupUpdate — Update cronjob group (POST /cronjobs/group/update)
func (s *CronjobService) POSTGroupUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/cronjobs/group/update", body)
}

// POSTHandle — Handle cronjob once (POST /cronjobs/handle)
func (s *CronjobService) POSTHandle(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/cronjobs/handle", body)
}

// POSTImport — Import cronjob list (POST /cronjobs/import)
func (s *CronjobService) POSTImport(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/cronjobs/import", body)
}

// POSTLoadInfo — Load cronjob info (POST /cronjobs/load/info)
func (s *CronjobService) POSTLoadInfo(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/cronjobs/load/info", body)
}

// POSTNext — Load cronjob spec time (POST /cronjobs/next)
func (s *CronjobService) POSTNext(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/cronjobs/next", body)
}

// POSTRecordsClean — Clean job records (POST /cronjobs/records/clean)
func (s *CronjobService) POSTRecordsClean(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/cronjobs/records/clean", body)
}

// POSTRecordsLog — Load Cronjob record log (POST /cronjobs/records/log)
func (s *CronjobService) POSTRecordsLog(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/cronjobs/records/log", body)
}

// GETScriptOptions — Load script options (GET /cronjobs/script/options)
func (s *CronjobService) GETScriptOptions(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/cronjobs/script/options")
}

// POSTSearch — Page cronjobs (POST /cronjobs/search)
func (s *CronjobService) POSTSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/cronjobs/search", body)
}

// POSTSearchRecords — Page job records (POST /cronjobs/search/records)
func (s *CronjobService) POSTSearchRecords(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/cronjobs/search/records", body)
}

// POSTStatus — Update cronjob status (POST /cronjobs/status)
func (s *CronjobService) POSTStatus(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/cronjobs/status", body)
}

// POSTStop — Handle stop job (POST /cronjobs/stop)
func (s *CronjobService) POSTStop(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/cronjobs/stop", body)
}

// POSTUpdate — Update cronjob (POST /cronjobs/update)
func (s *CronjobService) POSTUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/cronjobs/update", body)
}

