// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel
import (
	"context"
	"fmt"
)

// POSTBackups — Create backup account (POST /backups)
func (s *BackupService) POSTBackups(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups", body)
}

// POSTBackup — Backup system data (POST /backups/backup)
func (s *BackupService) POSTBackup(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/backup", body)
}

// POSTBuckets — List buckets (POST /backups/buckets)
func (s *BackupService) POSTBuckets(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/buckets", body)
}

// GETCheck — Check backup used (GET /backups/check/{name})
func (s *BackupService) GETCheck(ctx context.Context, name string) (map[string]any, error) {
	return s.getMap(ctx, fmt.Sprintf("/backups/check/%s", name))
}

// POSTConnCheck — Check backup account (POST /backups/conn/check)
func (s *BackupService) POSTConnCheck(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/conn/check", body)
}

// POSTDel — Delete backup account (POST /backups/del)
func (s *BackupService) POSTDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/del", body)
}

// GETLocal — get local backup dir (GET /backups/local)
func (s *BackupService) GETLocal(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/backups/local")
}

// GETOptions — Load backup account options (GET /backups/options)
func (s *BackupService) GETOptions(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/backups/options")
}

// POSTRecordDel — Delete backup record (POST /backups/record/del)
func (s *BackupService) POSTRecordDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/record/del", body)
}

// POSTRecordDescriptionUpdate — Update backup record description (POST /backups/record/description/update)
func (s *BackupService) POSTRecordDescriptionUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/record/description/update", body)
}

// POSTRecordDownload — Download backup record (POST /backups/record/download)
func (s *BackupService) POSTRecordDownload(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/record/download", body)
}

// POSTRecordSearch — Page backup records (POST /backups/record/search)
func (s *BackupService) POSTRecordSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/record/search", body)
}

// POSTRecordSearchBycronjob — Page backup records by cronjob (POST /backups/record/search/bycronjob)
func (s *BackupService) POSTRecordSearchBycronjob(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/record/search/bycronjob", body)
}

// POSTRecordSize — Load backup record size (POST /backups/record/size)
func (s *BackupService) POSTRecordSize(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/record/size", body)
}

// POSTRecover — Recover system data (POST /backups/recover)
func (s *BackupService) POSTRecover(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/recover", body)
}

// POSTRecoverByupload — Recover system data by upload (POST /backups/recover/byupload)
func (s *BackupService) POSTRecoverByupload(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/recover/byupload", body)
}

// POSTRefreshToken — Refresh token (POST /backups/refresh/token)
func (s *BackupService) POSTRefreshToken(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/refresh/token", body)
}

// POSTSearch — Search backup accounts with page (POST /backups/search)
func (s *BackupService) POSTSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/search", body)
}

// POSTSearchFiles — List files from backup accounts (POST /backups/search/files)
func (s *BackupService) POSTSearchFiles(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/search/files", body)
}

// POSTUpdate — Update backup account (POST /backups/update)
func (s *BackupService) POSTUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/update", body)
}

// POSTUpload — Upload file for recover (POST /backups/upload)
func (s *BackupService) POSTUpload(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/backups/upload", body)
}

