// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel
import (
	"context"
)

// POSTClam — Create clam (POST /toolbox/clam)
func (s *ToolboxService) POSTClam(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/clam", body)
}

// POSTClamBase — Load clam base info (POST /toolbox/clam/base)
func (s *ToolboxService) POSTClamBase(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/clam/base", body)
}

// POSTClamDel — Delete clam (POST /toolbox/clam/del)
func (s *ToolboxService) POSTClamDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/clam/del", body)
}

// POSTClamFileSearch — Load clam file (POST /toolbox/clam/file/search)
func (s *ToolboxService) POSTClamFileSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/clam/file/search", body)
}

// POSTClamFileUpdate — Update clam file (POST /toolbox/clam/file/update)
func (s *ToolboxService) POSTClamFileUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/clam/file/update", body)
}

// POSTClamHandle — Handle clam scan (POST /toolbox/clam/handle)
func (s *ToolboxService) POSTClamHandle(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/clam/handle", body)
}

// POSTClamOperate — Operate Clam (POST /toolbox/clam/operate)
func (s *ToolboxService) POSTClamOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/clam/operate", body)
}

// POSTClamRecordClean — Clean clam record (POST /toolbox/clam/record/clean)
func (s *ToolboxService) POSTClamRecordClean(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/clam/record/clean", body)
}

// POSTClamRecordSearch — Page clam record (POST /toolbox/clam/record/search)
func (s *ToolboxService) POSTClamRecordSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/clam/record/search", body)
}

// POSTClamSearch — Page clam (POST /toolbox/clam/search)
func (s *ToolboxService) POSTClamSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/clam/search", body)
}

// POSTClamStatusUpdate — Update clam status (POST /toolbox/clam/status/update)
func (s *ToolboxService) POSTClamStatusUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/clam/status/update", body)
}

// POSTClamUpdate — Update clam (POST /toolbox/clam/update)
func (s *ToolboxService) POSTClamUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/clam/update", body)
}

// POSTClean — Clean system (POST /toolbox/clean)
func (s *ToolboxService) POSTClean(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/clean", body)
}

// POSTDeviceBase — Load device base info (POST /toolbox/device/base)
func (s *ToolboxService) POSTDeviceBase(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/device/base", body)
}

// POSTDeviceCheckDns — Check device DNS conf (POST /toolbox/device/check/dns)
func (s *ToolboxService) POSTDeviceCheckDns(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/device/check/dns", body)
}

// POSTDeviceConf — load conf (POST /toolbox/device/conf)
func (s *ToolboxService) POSTDeviceConf(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/device/conf", body)
}

// POSTDeviceUpdateByconf — Update device conf by file (POST /toolbox/device/update/byconf)
func (s *ToolboxService) POSTDeviceUpdateByconf(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/device/update/byconf", body)
}

// POSTDeviceUpdateConf — Update device (POST /toolbox/device/update/conf)
func (s *ToolboxService) POSTDeviceUpdateConf(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/device/update/conf", body)
}

// POSTDeviceUpdateHost — Update device hosts (POST /toolbox/device/update/host)
func (s *ToolboxService) POSTDeviceUpdateHost(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/device/update/host", body)
}

// POSTDeviceUpdatePasswd — Update device passwd (POST /toolbox/device/update/passwd)
func (s *ToolboxService) POSTDeviceUpdatePasswd(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/device/update/passwd", body)
}

// POSTDeviceUpdateSwap — Update device swap (POST /toolbox/device/update/swap)
func (s *ToolboxService) POSTDeviceUpdateSwap(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/device/update/swap", body)
}

// GETDeviceUsers — Load user list (GET /toolbox/device/users)
func (s *ToolboxService) GETDeviceUsers(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/toolbox/device/users")
}

// GETDeviceZoneOptions — list time zone options (GET /toolbox/device/zone/options)
func (s *ToolboxService) GETDeviceZoneOptions(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/toolbox/device/zone/options")
}

// GETFail2banBase — Load fail2ban base info (GET /toolbox/fail2ban/base)
func (s *ToolboxService) GETFail2banBase(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/toolbox/fail2ban/base")
}

// GETFail2banLoadConf — Load fail2ban conf (GET /toolbox/fail2ban/load/conf)
func (s *ToolboxService) GETFail2banLoadConf(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/toolbox/fail2ban/load/conf")
}

// POSTFail2banOperate — Operate fail2ban (POST /toolbox/fail2ban/operate)
func (s *ToolboxService) POSTFail2banOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/fail2ban/operate", body)
}

// POSTFail2banOperateSshd — Operate sshd of fail2ban (POST /toolbox/fail2ban/operate/sshd)
func (s *ToolboxService) POSTFail2banOperateSshd(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/fail2ban/operate/sshd", body)
}

// POSTFail2banSearch — Page fail2ban ip list (POST /toolbox/fail2ban/search)
func (s *ToolboxService) POSTFail2banSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/fail2ban/search", body)
}

// POSTFail2banUpdate — Update fail2ban conf (POST /toolbox/fail2ban/update)
func (s *ToolboxService) POSTFail2banUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/fail2ban/update", body)
}

// POSTFail2banUpdateByconf — Update fail2ban conf by file (POST /toolbox/fail2ban/update/byconf)
func (s *ToolboxService) POSTFail2banUpdateByconf(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/fail2ban/update/byconf", body)
}

// POSTFtp — Create FTP user (POST /toolbox/ftp)
func (s *ToolboxService) POSTFtp(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/ftp", body)
}

// GETFtpBase — Load FTP base info (GET /toolbox/ftp/base)
func (s *ToolboxService) GETFtpBase(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/toolbox/ftp/base")
}

// POSTFtpDel — Delete FTP user (POST /toolbox/ftp/del)
func (s *ToolboxService) POSTFtpDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/ftp/del", body)
}

// POSTFtpLogSearch — Load FTP operation log (POST /toolbox/ftp/log/search)
func (s *ToolboxService) POSTFtpLogSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/ftp/log/search", body)
}

// POSTFtpOperate — Operate FTP (POST /toolbox/ftp/operate)
func (s *ToolboxService) POSTFtpOperate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/ftp/operate", body)
}

// POSTFtpSearch — Page FTP user (POST /toolbox/ftp/search)
func (s *ToolboxService) POSTFtpSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/ftp/search", body)
}

// POSTFtpSync — Sync FTP user (POST /toolbox/ftp/sync)
func (s *ToolboxService) POSTFtpSync(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/ftp/sync", body)
}

// POSTFtpUpdate — Update FTP user (POST /toolbox/ftp/update)
func (s *ToolboxService) POSTFtpUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/ftp/update", body)
}

// POSTScan — Scan system (POST /toolbox/scan)
func (s *ToolboxService) POSTScan(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/toolbox/scan", body)
}

