// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel
import (
	"context"
)

// POSTDatabases — Create mysql database (POST /databases)
func (s *DatabaseService) POSTDatabases(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases", body)
}

// POSTChangeAccess — Change mysql root access (POST /databases/change/access)
func (s *DatabaseService) POSTChangeAccess(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/change/access", body)
}

// POSTChangePassword — Change mysql root password (POST /databases/change/password)
func (s *DatabaseService) POSTChangePassword(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/change/password", body)
}

// POSTCommonInfo — Load base info (POST /databases/common/info)
func (s *DatabaseService) POSTCommonInfo(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/common/info", body)
}

// POSTCommonLoadFile — Load Database conf (POST /databases/common/load/file)
func (s *DatabaseService) POSTCommonLoadFile(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/common/load/file", body)
}

// POSTCommonUpdateConf — Update conf by upload file (POST /databases/common/update/conf)
func (s *DatabaseService) POSTCommonUpdateConf(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/common/update/conf", body)
}

// POSTDb — Create database (POST /databases/db)
func (s *DatabaseService) POSTDb(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/db", body)
}

// GETDbname — Get databases (GET /databases/db/:name)
func (s *DatabaseService) GETDbname(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/databases/db/:name")
}

// POSTDbCheck — Check database (POST /databases/db/check)
func (s *DatabaseService) POSTDbCheck(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/db/check", body)
}

// POSTDbDel — Delete database (POST /databases/db/del)
func (s *DatabaseService) POSTDbDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/db/del", body)
}

// POSTDbDelCheck — Check before delete remote database (POST /databases/db/del/check)
func (s *DatabaseService) POSTDbDelCheck(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/db/del/check", body)
}

// GETDbItemtype — List databases (GET /databases/db/item/:type)
func (s *DatabaseService) GETDbItemtype(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/databases/db/item/:type")
}

// GETDbListtype — List databases (GET /databases/db/list/:type)
func (s *DatabaseService) GETDbListtype(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/databases/db/list/:type")
}

// POSTDbSearch — Page databases (POST /databases/db/search)
func (s *DatabaseService) POSTDbSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/db/search", body)
}

// POSTDbUpdate — Update database (POST /databases/db/update)
func (s *DatabaseService) POSTDbUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/db/update", body)
}

// POSTDel — Delete mysql database (POST /databases/del)
func (s *DatabaseService) POSTDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/del", body)
}

// POSTDelCheck — Check before delete mysql database (POST /databases/del/check)
func (s *DatabaseService) POSTDelCheck(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/del/check", body)
}

// POSTDescriptionUpdate — Update mysql database description (POST /databases/description/update)
func (s *DatabaseService) POSTDescriptionUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/description/update", body)
}

// POSTFormatOptions — List mysql database format collation options (POST /databases/format/options)
func (s *DatabaseService) POSTFormatOptions(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/format/options", body)
}

// POSTGrants — Grant mysql user (POST /databases/grants)
func (s *DatabaseService) POSTGrants(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/grants", body)
}

// POSTGrantsDel — Revoke mysql grant (POST /databases/grants/del)
func (s *DatabaseService) POSTGrantsDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/grants/del", body)
}

// POSTGrantsSearch — List mysql grants (POST /databases/grants/search)
func (s *DatabaseService) POSTGrantsSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/grants/search", body)
}

// POSTGrantsSummary — List mysql grant summary (POST /databases/grants/summary)
func (s *DatabaseService) POSTGrantsSummary(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/grants/summary", body)
}

// POSTLoad — Load mysql database from remote (POST /databases/load)
func (s *DatabaseService) POSTLoad(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/load", body)
}

// POSTMongodb — Create mongodb database (POST /databases/mongodb)
func (s *DatabaseService) POSTMongodb(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/mongodb", body)
}

// POSTMongodbBind — Bind mongodb database user info (POST /databases/mongodb/bind)
func (s *DatabaseService) POSTMongodbBind(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/mongodb/bind", body)
}

// POSTMongodbDel — Delete mongodb database (POST /databases/mongodb/del)
func (s *DatabaseService) POSTMongodbDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/mongodb/del", body)
}

// POSTMongodbDelCheck — Check before delete mongodb database (POST /databases/mongodb/del/check)
func (s *DatabaseService) POSTMongodbDelCheck(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/mongodb/del/check", body)
}

// POSTMongodbDescription — Update mongodb database description (POST /databases/mongodb/description)
func (s *DatabaseService) POSTMongodbDescription(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/mongodb/description", body)
}

// POSTMongodbLoad — Load mongodb database from remote (POST /databases/mongodb/load)
func (s *DatabaseService) POSTMongodbLoad(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/mongodb/load", body)
}

// POSTMongodbPassword — Change mongodb database password (POST /databases/mongodb/password)
func (s *DatabaseService) POSTMongodbPassword(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/mongodb/password", body)
}

// POSTMongodbPrivileges — Load mongodb privileges (POST /databases/mongodb/privileges)
func (s *DatabaseService) POSTMongodbPrivileges(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/mongodb/privileges", body)
}

// POSTMongodbPrivilegesChange — Change mongodb privileges (POST /databases/mongodb/privileges/change)
func (s *DatabaseService) POSTMongodbPrivilegesChange(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/mongodb/privileges/change", body)
}

// POSTMongodbRootPassword — Change mongodb root password (POST /databases/mongodb/root/password)
func (s *DatabaseService) POSTMongodbRootPassword(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/mongodb/root/password", body)
}

// POSTMongodbSearch — Page mongodb databases (POST /databases/mongodb/search)
func (s *DatabaseService) POSTMongodbSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/mongodb/search", body)
}

// POSTPg — Create postgresql database (POST /databases/pg)
func (s *DatabaseService) POSTPg(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/pg", body)
}

// POSTPgdatabaseLoad — Load postgresql database from remote (POST /databases/pg/:database/load)
func (s *DatabaseService) POSTPgdatabaseLoad(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/pg/:database/load", body)
}

// POSTPgBind — Bind postgresql user (POST /databases/pg/bind)
func (s *DatabaseService) POSTPgBind(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/pg/bind", body)
}

// POSTPgDel — Delete postgresql database (POST /databases/pg/del)
func (s *DatabaseService) POSTPgDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/pg/del", body)
}

// POSTPgDelCheck — Check before delete postgresql database (POST /databases/pg/del/check)
func (s *DatabaseService) POSTPgDelCheck(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/pg/del/check", body)
}

// POSTPgDescription — Update postgresql database description (POST /databases/pg/description)
func (s *DatabaseService) POSTPgDescription(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/pg/description", body)
}

// POSTPgPassword — Change postgresql password (POST /databases/pg/password)
func (s *DatabaseService) POSTPgPassword(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/pg/password", body)
}

// POSTPgPrivileges — Change postgresql privileges (POST /databases/pg/privileges)
func (s *DatabaseService) POSTPgPrivileges(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/pg/privileges", body)
}

// POSTPgSearch — Page postgresql databases (POST /databases/pg/search)
func (s *DatabaseService) POSTPgSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/pg/search", body)
}

// GETRedisCheck — Check has cli (GET /databases/redis/check)
func (s *DatabaseService) GETRedisCheck(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/databases/redis/check")
}

// POSTRedisConf — Load redis conf (POST /databases/redis/conf)
func (s *DatabaseService) POSTRedisConf(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/redis/conf", body)
}

// POSTRedisConfUpdate — Update redis conf (POST /databases/redis/conf/update)
func (s *DatabaseService) POSTRedisConfUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/redis/conf/update", body)
}

// POSTRedisInstallCli — Install redis-cli (POST /databases/redis/install/cli)
func (s *DatabaseService) POSTRedisInstallCli(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/redis/install/cli", body)
}

// POSTRedisPassword — Change redis password (POST /databases/redis/password)
func (s *DatabaseService) POSTRedisPassword(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/redis/password", body)
}

// POSTRedisPersistenceConf — Load redis persistence conf (POST /databases/redis/persistence/conf)
func (s *DatabaseService) POSTRedisPersistenceConf(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/redis/persistence/conf", body)
}

// POSTRedisPersistenceUpdate — Update redis persistence conf (POST /databases/redis/persistence/update)
func (s *DatabaseService) POSTRedisPersistenceUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/redis/persistence/update", body)
}

// POSTRedisStatus — Load redis status info (POST /databases/redis/status)
func (s *DatabaseService) POSTRedisStatus(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/redis/status", body)
}

// POSTRemote — Load mysql remote access (POST /databases/remote)
func (s *DatabaseService) POSTRemote(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/remote", body)
}

// POSTSearch — Page mysql databases (POST /databases/search)
func (s *DatabaseService) POSTSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/search", body)
}

// POSTStatus — Load mysql status info (POST /databases/status)
func (s *DatabaseService) POSTStatus(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/status", body)
}

// POSTUsers — Create mysql user (POST /databases/users)
func (s *DatabaseService) POSTUsers(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/users", body)
}

// POSTUsersDel — Delete mysql user (POST /databases/users/del)
func (s *DatabaseService) POSTUsersDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/users/del", body)
}

// POSTUsersPassword — Change mysql user password (POST /databases/users/password)
func (s *DatabaseService) POSTUsersPassword(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/users/password", body)
}

// POSTUsersPasswordSave — Save mysql user password locally (POST /databases/users/password/save)
func (s *DatabaseService) POSTUsersPasswordSave(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/users/password/save", body)
}

// POSTUsersSearch — List mysql users (POST /databases/users/search)
func (s *DatabaseService) POSTUsersSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/users/search", body)
}

// POSTUsersUpdate — Update mysql user (POST /databases/users/update)
func (s *DatabaseService) POSTUsersUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/users/update", body)
}

// POSTVariables — Load mysql variables info (POST /databases/variables)
func (s *DatabaseService) POSTVariables(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/variables", body)
}

// POSTVariablesUpdate — Update mysql variables (POST /databases/variables/update)
func (s *DatabaseService) POSTVariablesUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/databases/variables/update", body)
}

