// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel

import (
	"context"
)

// GETkey — Search app by key (GET /apps/:key)
func (s *AppService) GETkey(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/apps/:key")
}

// GETCheckupdate — Get app list update (GET /apps/checkupdate)
func (s *AppService) GETCheckupdate(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/apps/checkupdate")
}

// GETDetailappidversiontype — Search app detail by appid (GET /apps/detail/:appId/:version/:type)
func (s *AppService) GETDetailappidversiontype(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/apps/detail/:appId/:version/:type")
}

// GETDetailNodeappkeyversion — Search app detail by appkey and version (GET /apps/detail/node/:appKey/:version)
func (s *AppService) GETDetailNodeappkeyversion(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/apps/detail/node/:appKey/:version")
}

// GETDetailsid — Get app detail by id (GET /apps/details/:id)
func (s *AppService) GETDetailsid(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/apps/details/:id")
}

// GETIconkey — Get app icon by app_id (GET /apps/icon/:key)
func (s *AppService) GETIconkey(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/apps/icon/:key")
}

// POSTIgnoredCancel — Cancel Ignore Upgrade App (POST /apps/ignored/cancel)
func (s *AppService) POSTIgnoredCancel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/ignored/cancel", body)
}

// GETIgnoredDetail — List Upgrade Ignored App (GET /apps/ignored/detail)
func (s *AppService) GETIgnoredDetail(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/apps/ignored/detail")
}

// POSTInstall — Install app (POST /apps/install)
func (s *AppService) POSTInstall(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/install", body)
}

// POSTInstalledCheck — Check app installed (POST /apps/installed/check)
func (s *AppService) POSTInstalledCheck(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/installed/check", body)
}

// POSTInstalledConf — Search default config by key (POST /apps/installed/conf)
func (s *AppService) POSTInstalledConf(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/installed/conf", body)
}

// POSTInstalledConfigUpdate — Update app config (POST /apps/installed/config/update)
func (s *AppService) POSTInstalledConfigUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/installed/config/update", body)
}

// POSTInstalledConninfo — Search app password by key (POST /apps/installed/conninfo)
func (s *AppService) POSTInstalledConninfo(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/installed/conninfo", body)
}

// GETInstalledDeleteCheckappinstallid — Check before delete (GET /apps/installed/delete/check/:appInstallId)
func (s *AppService) GETInstalledDeleteCheckappinstallid(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/apps/installed/delete/check/:appInstallId")
}

// POSTInstalledIgnore — Ignore Upgrade App (POST /apps/installed/ignore)
func (s *AppService) POSTInstalledIgnore(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/installed/ignore", body)
}

// GETInstalledInfoappinstallid — Get app install info (GET /apps/installed/info/:appInstallId)
func (s *AppService) GETInstalledInfoappinstallid(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/apps/installed/info/:appInstallId")
}

// GETInstalledList — List app installed (GET /apps/installed/list)
func (s *AppService) GETInstalledList(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/apps/installed/list")
}

// POSTInstalledLoadport — Search app port by key (POST /apps/installed/loadport)
func (s *AppService) POSTInstalledLoadport(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/installed/loadport", body)
}

// POSTInstalledOp — Operate installed app (POST /apps/installed/op)
func (s *AppService) POSTInstalledOp(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/installed/op", body)
}

// GETInstalledParamsappinstallid — Search params by appInstallId (GET /apps/installed/params/:appInstallId)
func (s *AppService) GETInstalledParamsappinstallid(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/apps/installed/params/:appInstallId")
}

// POSTInstalledParamsUpdate — Change app params (POST /apps/installed/params/update)
func (s *AppService) POSTInstalledParamsUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/installed/params/update", body)
}

// POSTInstalledPortChange — Change app port (POST /apps/installed/port/change)
func (s *AppService) POSTInstalledPortChange(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/installed/port/change", body)
}

// POSTInstalledSearch — Page app installed (POST /apps/installed/search)
func (s *AppService) POSTInstalledSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/installed/search", body)
}

// POSTInstalledSortUpdate — Update app install sort (POST /apps/installed/sort/update)
func (s *AppService) POSTInstalledSortUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/installed/sort/update", body)
}

// POSTInstalledSync — Sync app installed (POST /apps/installed/sync)
func (s *AppService) POSTInstalledSync(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/installed/sync", body)
}

// POSTInstalledUpdateVersions — Search app update version by install id (POST /apps/installed/update/versions)
func (s *AppService) POSTInstalledUpdateVersions(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/installed/update/versions", body)
}

// POSTSearch — List apps (POST /apps/search)
func (s *AppService) POSTSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/search", body)
}

// GETServiceskey — Search app service by key (GET /apps/services/:key)
func (s *AppService) GETServiceskey(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/apps/services/:key")
}

// POSTSyncLocal — Sync local  app list (POST /apps/sync/local)
func (s *AppService) POSTSyncLocal(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/sync/local", body)
}

// POSTSyncRemote — Sync remote app list (POST /apps/sync/remote)
func (s *AppService) POSTSyncRemote(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/apps/sync/remote", body)
}

// GETTags — Get app tags (GET /apps/tags)
func (s *AppService) GETTags(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/apps/tags")
}
