// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel

import (
	"context"
	"fmt"
)

// POSTListening — Get Listening Process (POST /process/listening)
func (s *ProcessService) POSTListening(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/process/listening", body)
}

// POSTStop — Stop Process (POST /process/stop)
func (s *ProcessService) POSTStop(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/process/stop", body)
}

// GETWs — Process ws (GET /process/ws)
func (s *ProcessService) GETWs(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/process/ws")
}

// GETProcess — Get Process Info By PID (GET /process/{pid})
func (s *ProcessService) GETProcess(ctx context.Context, pid string) (map[string]any, error) {
	return s.getMap(ctx, fmt.Sprintf("/process/%s", pid))
}
