// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel

import (
	"context"
)

// POSTAlert — Create alert (POST /alert)
func (s *AlertsService) POSTAlert(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/alert", body)
}

// GETClamsList — Get clams (GET /alert/clams/list)
func (s *AlertsService) GETClamsList(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/alert/clams/list")
}

// POSTConfigDel — Delete alert config (POST /alert/config/del)
func (s *AlertsService) POSTConfigDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/alert/config/del", body)
}

// POSTConfigInfo — Get alert config (POST /alert/config/info)
func (s *AlertsService) POSTConfigInfo(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/alert/config/info", body)
}

// POSTConfigSearch — Page alert config (POST /alert/config/search)
func (s *AlertsService) POSTConfigSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/alert/config/search", body)
}

// POSTConfigTest — Test alert config (POST /alert/config/test)
func (s *AlertsService) POSTConfigTest(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/alert/config/test", body)
}

// POSTConfigUpdate — Update alert config (POST /alert/config/update)
func (s *AlertsService) POSTConfigUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/alert/config/update", body)
}

// POSTCronjobList — Get cron jobs (POST /alert/cronjob/list)
func (s *AlertsService) POSTCronjobList(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/alert/cronjob/list", body)
}

// POSTDel — Delete alert (POST /alert/del)
func (s *AlertsService) POSTDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/alert/del", body)
}

// GETDisksList — Get disks (GET /alert/disks/list)
func (s *AlertsService) GETDisksList(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/alert/disks/list")
}

// POSTLogsClean — Clean alert logs (POST /alert/logs/clean)
func (s *AlertsService) POSTLogsClean(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/alert/logs/clean", body)
}

// POSTLogsSearch — Page alert logs (POST /alert/logs/search)
func (s *AlertsService) POSTLogsSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/alert/logs/search", body)
}

// POSTSearch — Page alert (POST /alert/search)
func (s *AlertsService) POSTSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/alert/search", body)
}

// POSTStatus — Update alert status (POST /alert/status)
func (s *AlertsService) POSTStatus(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/alert/status", body)
}

// POSTUpdate — Update alert (POST /alert/update)
func (s *AlertsService) POSTUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/alert/update", body)
}
