// Code generated by scripts/gen-from-swagger.py. DO NOT EDIT.
package onepanel
import (
	"context"
)

// CoreAuthService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type CoreAuthService struct { ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *CoreAuthService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTAuthApiGenerate — generate api key (POST /core/auth/api/generate)
func (s *CoreAuthService) POSTAuthApiGenerate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/auth/api/generate", body)
}

// POSTAuthApiUpdate — Update api config (POST /core/auth/api/update)
func (s *CoreAuthService) POSTAuthApiUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/auth/api/update", body)
}

// GETAuthCaptcha — Load captcha (GET /core/auth/captcha)
func (s *CoreAuthService) GETAuthCaptcha(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/core/auth/captcha")
}

// GETAuthCurrent — Load current user info (GET /core/auth/current)
func (s *CoreAuthService) GETAuthCurrent(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/core/auth/current")
}

// POSTAuthCurrentUpdate — Update current user info (POST /core/auth/current/update)
func (s *CoreAuthService) POSTAuthCurrentUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/auth/current/update", body)
}

// POSTAuthExpiredReset — Reset system password expired (POST /core/auth/expired/reset)
func (s *CoreAuthService) POSTAuthExpiredReset(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/auth/expired/reset", body)
}

// POSTAuthLogin — User login (POST /core/auth/login)
func (s *CoreAuthService) POSTAuthLogin(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/auth/login", body)
}

// POSTAuthMfa — Load mfa info (POST /core/auth/mfa)
func (s *CoreAuthService) POSTAuthMfa(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/auth/mfa", body)
}

// POSTAuthMfaBind — Bind mfa (POST /core/auth/mfa/bind)
func (s *CoreAuthService) POSTAuthMfaBind(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/auth/mfa/bind", body)
}

// POSTAuthMfaClose — Close mfa (POST /core/auth/mfa/close)
func (s *CoreAuthService) POSTAuthMfaClose(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/auth/mfa/close", body)
}

// POSTAuthMfalogin — User login with mfa (POST /core/auth/mfalogin)
func (s *CoreAuthService) POSTAuthMfalogin(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/auth/mfalogin", body)
}

// POSTAuthPasskeyBegin — User login with passkey (POST /core/auth/passkey/begin)
func (s *CoreAuthService) POSTAuthPasskeyBegin(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/auth/passkey/begin", body)
}

// POSTAuthPasskeyDel — Delete passkey (POST /core/auth/passkey/del)
func (s *CoreAuthService) POSTAuthPasskeyDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/auth/passkey/del", body)
}

// POSTAuthPasskeyFinish — User login with passkey (POST /core/auth/passkey/finish)
func (s *CoreAuthService) POSTAuthPasskeyFinish(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/auth/passkey/finish", body)
}

// GETAuthPasskeyList — List passkeys (GET /core/auth/passkey/list)
func (s *CoreAuthService) GETAuthPasskeyList(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/core/auth/passkey/list")
}

// POSTAuthPasskeyRegisterBegin — Begin passkey registration (POST /core/auth/passkey/register/begin)
func (s *CoreAuthService) POSTAuthPasskeyRegisterBegin(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/auth/passkey/register/begin", body)
}

// POSTAuthPasskeyRegisterFinish — Finish passkey registration (POST /core/auth/passkey/register/finish)
func (s *CoreAuthService) POSTAuthPasskeyRegisterFinish(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/auth/passkey/register/finish", body)
}

// GETAuthSetting — Get Setting For Login (GET /core/auth/setting)
func (s *CoreAuthService) GETAuthSetting(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/core/auth/setting")
}

// GETAuthWelcome — Get welcome page (GET /core/auth/welcome)
func (s *CoreAuthService) GETAuthWelcome(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/core/auth/welcome")
}

// CoreBackupsService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type CoreBackupsService struct { ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *CoreBackupsService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTBackups — Create backup account (POST /core/backups)
func (s *CoreBackupsService) POSTBackups(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/backups", body)
}

// GETBackupsClientclienttype — Load backup account base info (GET /core/backups/client/:clientType)
func (s *CoreBackupsService) GETBackupsClientclienttype(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/core/backups/client/:clientType")
}

// POSTBackupsDel — Delete backup account (POST /core/backups/del)
func (s *CoreBackupsService) POSTBackupsDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/backups/del", body)
}

// POSTBackupsRefreshToken — Refresh token (POST /core/backups/refresh/token)
func (s *CoreBackupsService) POSTBackupsRefreshToken(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/backups/refresh/token", body)
}

// POSTBackupsUpdate — Update backup account (POST /core/backups/update)
func (s *CoreBackupsService) POSTBackupsUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/backups/update", body)
}

// CoreCommandsService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type CoreCommandsService struct { ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *CoreCommandsService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTCommands — Create command (POST /core/commands)
func (s *CoreCommandsService) POSTCommands(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/commands", body)
}

// POSTCommandsDel — Delete command (POST /core/commands/del)
func (s *CoreCommandsService) POSTCommandsDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/commands/del", body)
}

// POSTCommandsExport — Export command (POST /core/commands/export)
func (s *CoreCommandsService) POSTCommandsExport(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/commands/export", body)
}

// POSTCommandsImport — Import command (POST /core/commands/import)
func (s *CoreCommandsService) POSTCommandsImport(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/commands/import", body)
}

// POSTCommandsList — List commands (POST /core/commands/list)
func (s *CoreCommandsService) POSTCommandsList(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/commands/list", body)
}

// POSTCommandsSearch — Page commands (POST /core/commands/search)
func (s *CoreCommandsService) POSTCommandsSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/commands/search", body)
}

// POSTCommandsTree — Tree commands (POST /core/commands/tree)
func (s *CoreCommandsService) POSTCommandsTree(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/commands/tree", body)
}

// POSTCommandsUpdate — Update command (POST /core/commands/update)
func (s *CoreCommandsService) POSTCommandsUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/commands/update", body)
}

// POSTCommandsUpload — Upload command csv for list (POST /core/commands/upload)
func (s *CoreCommandsService) POSTCommandsUpload(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/commands/upload", body)
}

// CoreGroupsService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type CoreGroupsService struct { ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *CoreGroupsService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTGroups — Create group (POST /core/groups)
func (s *CoreGroupsService) POSTGroups(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/groups", body)
}

// POSTGroupsDel — Delete group (POST /core/groups/del)
func (s *CoreGroupsService) POSTGroupsDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/groups/del", body)
}

// POSTGroupsSearch — List groups (POST /core/groups/search)
func (s *CoreGroupsService) POSTGroupsSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/groups/search", body)
}

// POSTGroupsUpdate — Update group (POST /core/groups/update)
func (s *CoreGroupsService) POSTGroupsUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/groups/update", body)
}

// CoreLogsService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type CoreLogsService struct { ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *CoreLogsService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTLogsClean — Clean operation logs (POST /core/logs/clean)
func (s *CoreLogsService) POSTLogsClean(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/logs/clean", body)
}

// POSTLogsLogin — Page login logs (POST /core/logs/login)
func (s *CoreLogsService) POSTLogsLogin(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/logs/login", body)
}

// POSTLogsOperation — Page operation logs (POST /core/logs/operation)
func (s *CoreLogsService) POSTLogsOperation(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/logs/operation", body)
}

// CoreScriptService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type CoreScriptService struct { ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *CoreScriptService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// POSTScript — Add script (POST /core/script)
func (s *CoreScriptService) POSTScript(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/script", body)
}

// POSTScriptDel — Delete script (POST /core/script/del)
func (s *CoreScriptService) POSTScriptDel(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/script/del", body)
}

// GETScriptRun — Run script (GET /core/script/run)
func (s *CoreScriptService) GETScriptRun(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/core/script/run")
}

// POSTScriptSearch — Page script (POST /core/script/search)
func (s *CoreScriptService) POSTScriptSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/script/search", body)
}

// POSTScriptSync — Sync script from remote (POST /core/script/sync)
func (s *CoreScriptService) POSTScriptSync(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/script/sync", body)
}

// POSTScriptUpdate — Update script (POST /core/script/update)
func (s *CoreScriptService) POSTScriptUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/script/update", body)
}

// CoreSettingsService covers endpoints not yet wrapped in typed methods. Use the
// generated per-endpoint helpers for full coverage.  See the
// 1Panel swagger.json for the original DTO definitions.
type CoreSettingsService struct { ServiceBase }

// Call invokes an arbitrary endpoint in this service.
func (s *CoreSettingsService) Call(ctx context.Context, method, path string, body, out any) error {
	return s.Do(ctx, method, path, body, out)
}

// GETSettingsAppsStoreConfig — Get appstore config (GET /core/settings/apps/store/config)
func (s *CoreSettingsService) GETSettingsAppsStoreConfig(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/core/settings/apps/store/config")
}

// POSTSettingsAppsStoreUpdate — Update appstore config (POST /core/settings/apps/store/update)
func (s *CoreSettingsService) POSTSettingsAppsStoreUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/apps/store/update", body)
}

// POSTSettingsBindUpdate — Update system bind info (POST /core/settings/bind/update)
func (s *CoreSettingsService) POSTSettingsBindUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/bind/update", body)
}

// GETSettingsInterface — Load system address (GET /core/settings/interface).
// Returns a top-level array of interface names — use GetList.
func (s *CoreSettingsService) GETSettingsInterface(ctx context.Context) ([]any, error) {
	return s.getList(ctx, "/core/settings/interface")
}

// GETSettingsMemo — Load dashboard memo (GET /core/settings/memo)
func (s *CoreSettingsService) GETSettingsMemo(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/core/settings/memo")
}

// POSTSettingsMemo — Update dashboard memo (POST /core/settings/memo)
func (s *CoreSettingsService) POSTSettingsMemo(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/memo", body)
}

// POSTSettingsMenuDefault — Default menu (POST /core/settings/menu/default)
func (s *CoreSettingsService) POSTSettingsMenuDefault(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/menu/default", body)
}

// POSTSettingsMenuUpdate — Update system setting (POST /core/settings/menu/update)
func (s *CoreSettingsService) POSTSettingsMenuUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/menu/update", body)
}

// POSTSettingsPortUpdate — Update system port (POST /core/settings/port/update)
func (s *CoreSettingsService) POSTSettingsPortUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/port/update", body)
}

// POSTSettingsProxyUpdate — Update proxy setting (POST /core/settings/proxy/update)
func (s *CoreSettingsService) POSTSettingsProxyUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/proxy/update", body)
}

// POSTSettingsSearch — Load system setting info (POST /core/settings/search)
func (s *CoreSettingsService) POSTSettingsSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/search", body)
}

// GETSettingsSearchAvailable — Load system available status (GET /core/settings/search/available)
func (s *CoreSettingsService) GETSettingsSearchAvailable(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/core/settings/search/available")
}

// POSTSettingsSearchBase — Load base system setting info (POST /core/settings/search/base)
func (s *CoreSettingsService) POSTSettingsSearchBase(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/search/base", body)
}

// POSTSettingsSslDownload — Download system cert (POST /core/settings/ssl/download)
func (s *CoreSettingsService) POSTSettingsSslDownload(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/ssl/download", body)
}

// GETSettingsSslInfo — Load system cert info (GET /core/settings/ssl/info)
func (s *CoreSettingsService) GETSettingsSslInfo(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/core/settings/ssl/info")
}

// POSTSettingsSslReload — Reload SSL (POST /core/settings/ssl/reload)
func (s *CoreSettingsService) POSTSettingsSslReload(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/ssl/reload", body)
}

// POSTSettingsSslUpdate — Update system ssl (POST /core/settings/ssl/update)
func (s *CoreSettingsService) POSTSettingsSslUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/ssl/update", body)
}

// POSTSettingsTerminalSearch — Load system terminal setting info (POST /core/settings/terminal/search)
func (s *CoreSettingsService) POSTSettingsTerminalSearch(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/terminal/search", body)
}

// POSTSettingsTerminalUpdate — Update system terminal setting (POST /core/settings/terminal/update)
func (s *CoreSettingsService) POSTSettingsTerminalUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/terminal/update", body)
}

// POSTSettingsUpdate — Update system setting (POST /core/settings/update)
func (s *CoreSettingsService) POSTSettingsUpdate(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/update", body)
}

// GETSettingsUpgrade — Load upgrade info (GET /core/settings/upgrade)
func (s *CoreSettingsService) GETSettingsUpgrade(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/core/settings/upgrade")
}

// POSTSettingsUpgrade — Upgrade (POST /core/settings/upgrade)
func (s *CoreSettingsService) POSTSettingsUpgrade(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/upgrade", body)
}

// POSTSettingsUpgradeNotes — Load release notes by version (POST /core/settings/upgrade/notes)
func (s *CoreSettingsService) POSTSettingsUpgradeNotes(ctx context.Context, body any) (map[string]any, error) {
	return s.postMap(ctx, "/core/settings/upgrade/notes", body)
}

// GETSettingsUpgradeReleases — Load upgrade notes (GET /core/settings/upgrade/releases)
func (s *CoreSettingsService) GETSettingsUpgradeReleases(ctx context.Context) (map[string]any, error) {
	return s.getMap(ctx, "/core/settings/upgrade/releases")
}

